using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SenateData.DataModels.Common;
namespace SenateData.Configurations
{
    public class BranchSeeder: IEntityTypeConfiguration<Branch>
    {
        public void Configure(EntityTypeBuilder<Branch> builder)
        {
            builder.HasData(
                new Branch { Id = 1, Description = "Senator Service Centre", IsActive = true, },
                new Branch { Id = 2, Description = "Question Branch", IsActive = true, },
                new Branch { Id = 3, Description = "Legislation", IsActive = true, },
                new Branch { Id = 4, Description = "Committee Branch (II)", IsActive = true, },
                new Branch { Id = 5, Description = "Translation Branch", IsActive = true, },
                new Branch { Id = 6, Description = "Transport Branch", IsActive = true, },
                new Branch { Id = 7, Description = "Motion Branch", IsActive = true, },
                new Branch { Id = 8, Description = "Reporting Cell", IsActive = true, },
                new Branch { Id = 9, Description = "Cash and Account ", IsActive = true, },
                new Branch { Id = 10, Description = "Finance and Accounts Branch", IsActive = true, },
                new Branch { Id = 11, Description = "Library", IsActive = true, },
                new Branch { Id = 12, Description = "Media ", IsActive = false, },
                new Branch { Id = 13, Description = "IPR", IsActive = true, },
                new Branch { Id = 14, Description = "Additional Secretary Admin Office", IsActive = true, },
                new Branch { Id = 15, Description = "Additional Secretary (COMM) Office", IsActive = true, },
                new Branch { Id = 16, Description = "Administration ", IsActive = true, },
                new Branch { Id = 17, Description = "Chairman Office", IsActive = true, },
                new Branch { Id = 18, Description = "Committee Branch (I)", IsActive = true, },
                new Branch { Id = 19, Description = "COMM-II,TRANS.CELL", IsActive = false, },
                new Branch { Id = 20, Description = "Committee Branch (III)", IsActive = true, },
                new Branch { Id = 21, Description = "COM-I BR.", IsActive = false, },
                new Branch { Id = 22, Description = "Committee Branch IV", IsActive = false, },
                new Branch { Id = 23, Description = "IT-Directorate", IsActive = true, },
                new Branch { Id = 24, Description = "Consultant Office", IsActive = false, },
                new Branch { Id = 25, Description = "Public Relations Cell", IsActive = true, },
                new Branch { Id = 26, Description = "Committee Branch I", IsActive = false, },
                new Branch { Id = 27, Description = "HRM", IsActive = true, },
                new Branch { Id = 28, Description = "Deputy Chairman Office", IsActive = true, },
                new Branch { Id = 29, Description = "Debates Branch", IsActive = true, },
                new Branch { Id = 30, Description = "Engineering Cell", IsActive = false, },
                new Branch { Id = 31, Description = "Interpretation Cell", IsActive = true, },
                new Branch { Id = 32, Description = "(A) OFFICE", IsActive = false, },
                new Branch { Id = 33, Description = "P.R CELL", IsActive = false, },
                new Branch { Id = 34, Description = "(C) Office", IsActive = false, },
                new Branch { Id = 35, Description = "Printing Branch", IsActive = true, },
                new Branch { Id = 36, Description = "Printing Shop", IsActive = false, },
                new Branch { Id = 37, Description = "Protocol Cell", IsActive = true, },
                new Branch { Id = 38, Description = "QAP BRANCH", IsActive = true, },
                new Branch { Id = 39, Description = "Receipt and Issue Branch", IsActive = true, },
                new Branch { Id = 40, Description = "Reporters Cell", IsActive = true, },
                new Branch { Id = 41, Description = "Research Cell", IsActive = true, },
                new Branch { Id = 42, Description = "Security Branch", IsActive = false, },
                new Branch { Id = 43, Description = "Services", IsActive = true, },
                new Branch { Id = 44, Description = "SIS", IsActive = true, },
                new Branch { Id = 45, Description = "ADMN + R&I BR.", IsActive = false, },
                new Branch { Id = 46, Description = "ADMN + TRANSP.BR.", IsActive = false, },
                new Branch { Id = 47, Description = "ADMN.ESTT BR.", IsActive = false, },
                new Branch { Id = 48, Description = "Budget & Accounts Branch", IsActive = false, },
                new Branch { Id = 49, Description = "CASH & ACCTT/COMMT.", IsActive = false, },
                new Branch { Id = 50, Description = "Chairman Standing Committee", IsActive = true, },
                new Branch { Id = 52, Description = "COMM-I-II & R&I BR.", IsActive = false, },
                new Branch { Id = 53, Description = "COMM-III & PRINT.BR.", IsActive = false, },
                new Branch { Id = 54, Description = "COMM-III & R&I BR.", IsActive = false, },
                new Branch { Id = 55, Description = "ESTAB.ADMN.TRANS.", IsActive = false, },
                new Branch { Id = 56, Description = "ESTT. + RECORD BR.", IsActive = false, },
                new Branch { Id = 57, Description = "ESTT.IPR.", IsActive = false, },
                new Branch { Id = 58, Description = "F&A,ADMN,C&A.", IsActive = false, },
                new Branch { Id = 59, Description = "I.P.R. + SERVICE BR.", IsActive = false, },
                new Branch { Id = 60, Description = "IPR BR.ESTT.BR.", IsActive = false, },
                new Branch { Id = 61, Description = "Joint Secretary Office", IsActive = true, },
                new Branch { Id = 62, Description = "Chairman Residence", IsActive = true, },
                new Branch { Id = 63, Description = "Office of the Leader of the House", IsActive = true, },
                new Branch { Id = 64, Description = "LEGIS/QAP/MOTION BR.", IsActive = false, },
                new Branch { Id = 65, Description = "N/O & R & I BRANCH", IsActive = false, },
                new Branch { Id = 66, Description = "PR/IPR BRANCH", IsActive = false, },
                new Branch { Id = 67, Description = "PR/IPR/NOTICE OFFICE", IsActive = false, },
                new Branch { Id = 68, Description = "PRINT.&.R&I", IsActive = false, },
                new Branch { Id = 69, Description = "PRINT.&.SERVI.BR", IsActive = false, },
                new Branch { Id = 70, Description = "PRINT.TRANS.SSC.", IsActive = false, },
                new Branch { Id = 71, Description = "PRINTING BR/S.S.C", IsActive = false, },
                new Branch { Id = 72, Description = "Q.A.P.& PRINTING", IsActive = false, },
                new Branch { Id = 73, Description = "QAP,TRANSPORT", IsActive = false, },
                new Branch { Id = 74, Description = "Record Branch", IsActive = true, },
                new Branch { Id = 75, Description = "Residence Leader of House", IsActive = true, },
                new Branch { Id = 76, Description = "Secretary Office", IsActive = true, },
                new Branch { Id = 77, Description = "Committee VI", IsActive = false, },
                new Branch { Id = 78, Description = "Senate Lounge", IsActive = true, },
                new Branch { Id = 79, Description = "SERVICE,RECORD BR", IsActive = false, },
                new Branch { Id = 80, Description = "TRANSF CML SECTT RWP", IsActive = false, },
                new Branch { Id = 81, Description = "Reproduction Unit", IsActive = true, },
                new Branch { Id = 82, Description = "Invitation Cell", IsActive = true, },
                new Branch { Id = 83, Description = "Editors Branch", IsActive = true, },
                new Branch { Id = 84, Description = "Hiring Branch", IsActive = true, },
                new Branch { Id = 85, Description = "Office of the Leader of the Opposition", IsActive = true, },
                new Branch { Id = 86, Description = "Senate Secretariat", IsActive = true, },
                new Branch { Id = 87, Description = "Complaint Cell", IsActive = true, },
                new Branch { Id = 88, Description = "Senate Standing Committee", IsActive = true, },
                new Branch { Id = 89, Description = "Special Secretary Office", IsActive = true, },
                new Branch { Id = 90, Description = "Planning ", IsActive = true, },
                new Branch { Id = 91, Description = "Question/Motion Branch", IsActive = true, },
                new Branch { Id = 92, Description = "Camp Office Quetta", IsActive = true, },
                new Branch { Id = 93, Description = "Camp Office Karachi", IsActive = true, },
                new Branch { Id = 94, Description = "Cabinet Division", IsActive = false, },
                new Branch { Id = 95, Description = "Camp Office Lahore", IsActive = true, },
                new Branch { Id = 96, Description = "Security", IsActive = true, },
                new Branch { Id = 97, Description = "Cafeteria", IsActive = true, },
                new Branch { Id = 98, Description = "Legislation II", IsActive = true, },
                new Branch { Id = 99, Description = "HRD Branch", IsActive = true, },
                new Branch { Id = 100, Description = "Committees", IsActive = true, },
                new Branch { Id = 101, Description = "Public Petition Cell", IsActive = true, },
                new Branch { Id = 102, Description = "DPR Branch", IsActive = true, },
                new Branch { Id = 103, Description = "HRM-II", IsActive = true, },
                new Branch { Id = 104, Description = "Admin-II", IsActive = true, },
                new Branch { Id = 105, Description = "Legislative Drafting Unit", IsActive = true, },
                new Branch { Id = 106, Description = "ML&R", IsActive = true, },
                new Branch { Id = 107, Description = "IPR-II", IsActive = true, },
                new Branch { Id = 108, Description = "HRM-III", IsActive = true, },
                new Branch { Id = 109, Description = "Lady Senator Services Center", IsActive = true, },
                new Branch { Id = 110, Description = "Sub-Office Karachi", IsActive = true, },
                new Branch { Id = 111, Description = "Chairman Functional Committee", IsActive = true, },
                new Branch { Id = 112, Description = "Coordination", IsActive = true, },
                new Branch { Id = 113, Description = "Posted with Senator", IsActive = true, },
                new Branch { Id = 114, Description = "Chief Whip (Office)", IsActive = true, },
                new Branch { Id = 115, Description = "Consultant's Office", IsActive = true, },
                new Branch { Id = 116, Description = "Ex-Chairman Senate", IsActive = true, },
                new Branch { Id = 117, Description = "Senate Forum for Policy Research", IsActive = true, },
                new Branch { Id = 118, Description = "IPR-I", IsActive = true, },
                new Branch { Id = 119, Description = "Admin-I", IsActive = true, },
                new Branch { Id = 120, Description = "Committee Branch", IsActive = true, },
                new Branch { Id = 121, Description = "Legislation-I", IsActive = true, },
                new Branch { Id = 122, Description = "Notice Office", IsActive = true, },
                new Branch { Id = 123, Description = "HRM-I", IsActive = true, },
                new Branch { Id = 124, Description = "Senate Announciator Cell", IsActive = true, },
                new Branch { Id = 125, Description = "Media Cell", IsActive = true, },
                new Branch { Id = 126, Description = "Camp Office (Islamabad International Airport) ", IsActive = true, },
                new Branch { Id = 127, Description = "U.S AID Building", IsActive = true, },
                new Branch { Id = 128, Description = "Additional Secretary Office", IsActive = true, },
                new Branch { Id = 129, Description = "Advisor to Chairman", IsActive = true, },
                new Branch { Id = 130, Description = "Senate Functional Committee", IsActive = true, },
                new Branch { Id = 131, Description = "Printing & Publication", IsActive = true, },
                new Branch { Id = 132, Description = "HRM Pool", IsActive = true, },
                new Branch { Id = 133, Description = "Empty", IsActive = false, },
                new Branch { Id = 134, Description = "Litigation", IsActive = true, },
                new Branch { Id = 135, Description = "Project Management Unit (PMU)", IsActive = true, },
                new Branch { Id = 136, Description = "R&I C-Block", IsActive = true, },
                new Branch { Id = 137, Description = "IPC", IsActive = true, },
                new Branch { Id = 138, Description = "Senior D.G Office", IsActive = true, },
                new Branch { Id = 139, Description = "IPR Wing", IsActive = true, },
                new Branch { Id = 140, Description = "Office of the Director General (IT)", IsActive = true, },
                new Branch { Id = 141, Description = "HRM-Database", IsActive = true, },
                new Branch { Id = 142, Description = "Parliamentary Development Unit (PDU)", IsActive = true, },
                new Branch { Id = 143, Description = "Office of the DS (HRM)", IsActive = true, },
                new Branch { Id = 144, Description = "IT Branch", IsActive = true, },
                new Branch { Id = 145, Description = "Office of Deputy Secretary", IsActive = true, },
                new Branch { Id = 146, Description = "Office of Section Officer", IsActive = true, },
                new Branch { Id = 147, Description = "Service Branch", IsActive = true, },
                new Branch { Id = 148, Description = "R&I", IsActive = true, },
                new Branch { Id = 149, Description = "HRM Branch-I (Pool)", IsActive = true, },
                new Branch { Id = 150, Description = "HRM Branch-II (Pool)", IsActive = true, },
                new Branch { Id = 151, Description = "Main Gate Block-C", IsActive = true, },
                new Branch { Id = 152, Description = "DDO (Office)", IsActive = true, },
                new Branch { Id = 153, Description = "Office of Joint Secretary", IsActive = true, },
                new Branch { Id = 154, Description = "Camp Office Peshawar", IsActive = true, },
                new Branch { Id = 155, Description = "Office of Director (IT)", IsActive = true, },
                new Branch { Id = 156, Description = "IT Directorate (C-Block)", IsActive = true, },
                new Branch { Id = 157, Description = "C-Block", IsActive = true, },
                new Branch { Id = 158, Description = "Parliament Building", IsActive = true, },
                new Branch { Id = 159, Description = "With Senator", IsActive = false, },
                new Branch { Id = 160, Description = "Office of the Section Officer", IsActive = true, },
                new Branch { Id = 161, Description = "Office of D.G", IsActive = true, },
                new Branch { Id = 162, Description = "EPC (Education Parliamentarian's Caucus)", IsActive = true, },
                new Branch { Id = 163, Description = "Telephone Exchange (Block-C)", IsActive = true, },
                new Branch { Id = 164, Description = "Residence of Dy. Chairman", IsActive = true, },
                new Branch { Id = 165, Description = "Office of the Parliamentary Party Leader (PMLN)", IsActive = true, },
                new Branch { Id = 166, Description = "Office of D.D (IT)", IsActive = true, },
                new Branch { Id = 167, Description = "Chief Minister's Secretariat, Quetta", IsActive = true, },
                new Branch { Id = 168, Description = "Office of the D.G (PDU)", IsActive = true, }

                );
        }
    }
}
