using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SenateData.DataModels.Common;
namespace SenateData.Configurations
{
    public class CitySeeder: IEntityTypeConfiguration<City>
    {
        public void Configure(EntityTypeBuilder<City> builder)
        {
            builder.HasData(
                new City { Id = 1, Description = "Abbottabad", IsActive = true, IsDistrict = true, },
                new City { Id = 2, Description = "Attock", IsActive = true, IsDistrict = true, },
                new City { Id = 3, Description = "Badin", IsActive = true, IsDistrict = true, },
                new City { Id = 4, Description = "Bagh (A.J.K)", IsActive = true, IsDistrict = true, },
                new City { Id = 5, Description = "Bahawalnagar", IsActive = true, IsDistrict = true, },
                new City { Id = 6, Description = "Bahawalpur ", IsActive = true, IsDistrict = true, },
                new City { Id = 7, Description = "Balakot", IsActive = true, IsDistrict = true, },
                new City { Id = 8, Description = "Bannu", IsActive = true, IsDistrict = true, },
                new City { Id = 9, Description = "Bhakkar", IsActive = true, IsDistrict = true, },
                new City { Id = 10, Description = "Chakwal", IsActive = true, IsDistrict = true, },
                new City { Id = 11, Description = "Charsadda", IsActive = true, IsDistrict = true, },
                new City { Id = 12, Description = "Chitral ", IsActive = true, IsDistrict = true, },
                new City { Id = 13, Description = "Ckaklala Cantt", IsActive = true, IsDistrict = true, },
                new City { Id = 14, Description = "Dera Ghazi Khan", IsActive = true, IsDistrict = true, },
                new City { Id = 15, Description = "Dera Ismail Khan", IsActive = true, IsDistrict = true, },
                new City { Id = 16, Description = "Dir", IsActive = true, IsDistrict = true, },
                new City { Id = 17, Description = "Faisalabad ", IsActive = true, IsDistrict = true, },
                new City { Id = 18, Description = "Fateh Jang", IsActive = true, IsDistrict = true, },
                new City { Id = 19, Description = "Gilgit", IsActive = true, IsDistrict = true, },
                new City { Id = 20, Description = "Gujar Khan", IsActive = true, IsDistrict = true, },
                new City { Id = 21, Description = "Gujranwala ", IsActive = true, IsDistrict = true, },
                new City { Id = 22, Description = "Gujrat", IsActive = true, IsDistrict = true, },
                new City { Id = 23, Description = "Gwader", IsActive = true, IsDistrict = true, },
                new City { Id = 24, Description = "Haripur", IsActive = true, IsDistrict = true, },
                new City { Id = 25, Description = "Hasan Abdal", IsActive = true, IsDistrict = true, },
                new City { Id = 26, Description = "Hyderabad", IsActive = true, IsDistrict = true, },
                new City { Id = 27, Description = "Islamabad", IsActive = true, IsDistrict = true, },
                new City { Id = 28, Description = "Jacobabad", IsActive = true, IsDistrict = true, },
                new City { Id = 29, Description = "Jang Shahi", IsActive = true, IsDistrict = true, },
                new City { Id = 30, Description = "Jhang", IsActive = true, IsDistrict = true, },
                new City { Id = 31, Description = "Jhelum ", IsActive = true, IsDistrict = true, },
                new City { Id = 32, Description = "Kalar Syedian", IsActive = true, IsDistrict = true, },
                new City { Id = 33, Description = "Kalat", IsActive = true, IsDistrict = true, },
                new City { Id = 34, Description = "Kamo Ke ", IsActive = true, IsDistrict = true, },
                new City { Id = 35, Description = "Karachi", IsActive = true, IsDistrict = true, },
                new City { Id = 36, Description = "Karak", IsActive = true, IsDistrict = true, },
                new City { Id = 37, Description = "Kasur", IsActive = true, IsDistrict = true, },
                new City { Id = 38, Description = "Khairpur", IsActive = true, IsDistrict = true, },
                new City { Id = 39, Description = "Khanewal", IsActive = true, IsDistrict = true, },
                new City { Id = 40, Description = "Khushab", IsActive = true, IsDistrict = true, },
                new City { Id = 41, Description = "Khuzdar", IsActive = true, IsDistrict = true, },
                new City { Id = 42, Description = "Kohat", IsActive = true, IsDistrict = true, },
                new City { Id = 43, Description = "Kotri", IsActive = true, IsDistrict = true, },
                new City { Id = 44, Description = "Lahore", IsActive = true, IsDistrict = true, },
                new City { Id = 45, Description = "Larkana", IsActive = true, IsDistrict = true, },
                new City { Id = 46, Description = "Leiah", IsActive = true, IsDistrict = true, },
                new City { Id = 47, Description = "Mandi Bahauddin", IsActive = true, IsDistrict = true, },
                new City { Id = 48, Description = "Mansehra", IsActive = true, IsDistrict = true, },
                new City { Id = 49, Description = "Mardan", IsActive = true, IsDistrict = true, },
                new City { Id = 50, Description = "Mianwali", IsActive = true, IsDistrict = true, },
                new City { Id = 51, Description = "Mirpur (A.J.K.)", IsActive = true, IsDistrict = true, },
                new City { Id = 52, Description = "Mirpur Khas", IsActive = true, IsDistrict = true, },
                new City { Id = 53, Description = "Multan ", IsActive = true, IsDistrict = true, },
                new City { Id = 54, Description = "Murree", IsActive = true, IsDistrict = true, },
                new City { Id = 55, Description = "Muzaffarabad (A.J.K.)", IsActive = true, IsDistrict = true, },
                new City { Id = 56, Description = "Narowal", IsActive = true, IsDistrict = true, },
                new City { Id = 57, Description = "Nawab Shah", IsActive = true, IsDistrict = true, },
                new City { Id = 58, Description = "Nowshera", IsActive = true, IsDistrict = true, },
                new City { Id = 59, Description = "Okara", IsActive = true, IsDistrict = true, },
                new City { Id = 60, Description = "Parachinar", IsActive = true, IsDistrict = true, },
                new City { Id = 61, Description = "Peshawar ", IsActive = true, IsDistrict = true, },
                new City { Id = 62, Description = "Quetta", IsActive = true, IsDistrict = true, },
                new City { Id = 63, Description = "Rahim Yar Khan", IsActive = true, IsDistrict = true, },
                new City { Id = 64, Description = "Rawalakot (A.J.K)", IsActive = true, IsDistrict = true, },
                new City { Id = 65, Description = "Rawalpindi", IsActive = true, IsDistrict = true, },
                new City { Id = 66, Description = "Risalpur", IsActive = true, IsDistrict = true, },
                new City { Id = 67, Description = "Sahiwal", IsActive = true, IsDistrict = true, },
                new City { Id = 68, Description = "Saidu Sharif", IsActive = true, IsDistrict = true, },
                new City { Id = 69, Description = "Sanghar", IsActive = true, IsDistrict = true, },
                new City { Id = 70, Description = "Sargodha ", IsActive = true, IsDistrict = true, },
                new City { Id = 71, Description = "Sawabi", IsActive = true, IsDistrict = true, },
                new City { Id = 72, Description = "Sheikhupura", IsActive = true, IsDistrict = true, },
                new City { Id = 73, Description = "Sialkot ", IsActive = true, IsDistrict = true, },
                new City { Id = 74, Description = "Sibi", IsActive = true, IsDistrict = true, },
                new City { Id = 75, Description = "Sujawal", IsActive = true, IsDistrict = true, },
                new City { Id = 76, Description = "Sukkur", IsActive = true, IsDistrict = true, },
                new City { Id = 77, Description = "Talagang", IsActive = true, IsDistrict = true, },
                new City { Id = 78, Description = "Taxila", IsActive = true, IsDistrict = true, },
                new City { Id = 79, Description = "Toba Tek Singh", IsActive = true, IsDistrict = true, },
                new City { Id = 80, Description = "Turbat", IsActive = true, IsDistrict = true, },
                new City { Id = 81, Description = "Vehari", IsActive = true, IsDistrict = true, },
                new City { Id = 82, Description = "Wah Cantt", IsActive = true, IsDistrict = true, },
                new City { Id = 83, Description = "Wazir Abad", IsActive = true, IsDistrict = true, },
                new City { Id = 84, Description = "Kashmore", IsActive = true, IsDistrict = true, },
                new City { Id = 85, Description = "Khyber Agency", IsActive = true, IsDistrict = true, },
                new City { Id = 86, Description = "Bajur Agency", IsActive = true, IsDistrict = true, },
                new City { Id = 87, Description = "Mohmand Agency", IsActive = true, IsDistrict = true, },
                new City { Id = 88, Description = "Orakzai Agency", IsActive = true, IsDistrict = true, },
                new City { Id = 89, Description = "Kurram Agency", IsActive = true, IsDistrict = true, },
                new City { Id = 90, Description = "North Waziristan Agency", IsActive = true, IsDistrict = true, },
                new City { Id = 91, Description = "South Waziristan Agency", IsActive = true, IsDistrict = true, },
                new City { Id = 92, Description = "F.R. Peshawar", IsActive = true, IsDistrict = true, },
                new City { Id = 93, Description = "F.R. Kohat", IsActive = true, IsDistrict = true, },
                new City { Id = 94, Description = "F.R. Lakki Marwat", IsActive = true, IsDistrict = true, },
                new City { Id = 95, Description = "F.R. Bannu", IsActive = true, IsDistrict = true, },
                new City { Id = 96, Description = "F.R. Tank", IsActive = true, IsDistrict = true, },
                new City { Id = 97, Description = "Muzaffargarh", IsActive = true, IsDistrict = true, },
                new City { Id = 98, Description = "Tharparker", IsActive = true, IsDistrict = true, },
                new City { Id = 99, Description = "Battagram", IsActive = true, IsDistrict = true, },
                new City { Id = 100, Description = "Rajan Pur", IsActive = true, IsDistrict = true, },
                new City { Id = 101, Description = "Shikarpur", IsActive = true, IsDistrict = true, },
                new City { Id = 102, Description = "Badin", IsActive = true, IsDistrict = false, },
                new City { Id = 103, Description = "Naushahro Feroze", IsActive = true, IsDistrict = true, },
                new City { Id = 104, Description = "Lakki Marwat", IsActive = true, IsDistrict = true, },
                new City { Id = 105, Description = "Pakpattan", IsActive = true, IsDistrict = true, },
                new City { Id = 106, Description = "Hangu", IsActive = true, IsDistrict = true, },
                new City { Id = 107, Description = "Neelum valley", IsActive = true, IsDistrict = true, },
                new City { Id = 108, Description = "Dadu", IsActive = true, IsDistrict = true, },
                new City { Id = 109, Description = "Zhob", IsActive = true, IsDistrict = true, },
                new City { Id = 110, Description = "Sherani", IsActive = true, IsDistrict = true, },
                new City { Id = 111, Description = "Shaheed Benazir Abad", IsActive = true, IsDistrict = true, },
                new City { Id = 112, Description = "Chishtiabad", IsActive = true, IsDistrict = true, },
                new City { Id = 113, Description = "Noshki", IsActive = true, IsDistrict = true, },
                new City { Id = 114, Description = "Kalar Kahar", IsActive = false, IsDistrict = true, },
                new City { Id = 115, Description = "zzzzzzzz", IsActive = true, IsDistrict = false, },
                new City { Id = 116, Description = "Umer Kot", IsActive = true, IsDistrict = true, },
                new City { Id = 117, Description = "Jamshoro", IsActive = true, IsDistrict = true, },
                new City { Id = 118, Description = "Poonch", IsActive = true, IsDistrict = true, },
                new City { Id = 119, Description = "Shahdad Kot", IsActive = true, IsDistrict = true, },
                new City { Id = 120, Description = "Lasbela", IsActive = true, IsDistrict = true, },
                new City { Id = 121, Description = "Kabul", IsActive = true, IsDistrict = true, },
                new City { Id = 122, Description = "Mazar-e-Sharif", IsActive = true, IsDistrict = true, },
                new City { Id = 123, Description = "Jalalabad", IsActive = true, IsDistrict = true, },
                new City { Id = 124, Description = "Tirana", IsActive = true, IsDistrict = true, },
                new City { Id = 125, Description = "Durres", IsActive = true, IsDistrict = true, },
                new City { Id = 126, Description = "Lezha", IsActive = true, IsDistrict = true, },
                new City { Id = 127, Description = "Gjirokastra", IsActive = true, IsDistrict = true, },
                new City { Id = 128, Description = "Shkodra", IsActive = true, IsDistrict = true, },
                new City { Id = 129, Description = "Algiers", IsActive = true, IsDistrict = true, },
                new City { Id = 130, Description = "Oran", IsActive = true, IsDistrict = true, },
                new City { Id = 131, Description = "Tamanrasset", IsActive = true, IsDistrict = true, },
                new City { Id = 132, Description = "Annaba ", IsActive = true, IsDistrict = true, },
                new City { Id = 133, Description = "Constantine", IsActive = true, IsDistrict = true, },
                new City { Id = 134, Description = "Luanda", IsActive = true, IsDistrict = true, },
                new City { Id = 135, Description = "Benguela", IsActive = true, IsDistrict = true, },
                new City { Id = 136, Description = "Cabinda", IsActive = true, IsDistrict = true, },
                new City { Id = 137, Description = "Lobito", IsActive = true, IsDistrict = true, },
                new City { Id = 138, Description = "Lubango", IsActive = true, IsDistrict = true, },
                new City { Id = 139, Description = "Menogue", IsActive = true, IsDistrict = true, },
                new City { Id = 140, Description = "Unge", IsActive = true, IsDistrict = true, },
                new City { Id = 141, Description = "Antigua ", IsActive = true, IsDistrict = true, },
                new City { Id = 142, Description = "Barbuda", IsActive = true, IsDistrict = true, },
                new City { Id = 143, Description = "Buenos Aires", IsActive = true, IsDistrict = true, },
                new City { Id = 144, Description = "Bariloche", IsActive = true, IsDistrict = true, },
                new City { Id = 145, Description = "Chubut", IsActive = true, IsDistrict = true, },
                new City { Id = 146, Description = "Cordoba ", IsActive = true, IsDistrict = true, },
                new City { Id = 147, Description = "Mal del Plata", IsActive = true, IsDistrict = true, },
                new City { Id = 148, Description = "Mendoza", IsActive = true, IsDistrict = true, },
                new City { Id = 149, Description = "Ushuaia", IsActive = true, IsDistrict = true, },
                new City { Id = 150, Description = "Canberra", IsActive = true, IsDistrict = true, },
                new City { Id = 151, Description = "Hobart", IsActive = true, IsDistrict = true, },
                new City { Id = 152, Description = "Melbourne", IsActive = true, IsDistrict = true, },
                new City { Id = 153, Description = "Darwing", IsActive = true, IsDistrict = true, },
                new City { Id = 154, Description = "Surfers", IsActive = true, IsDistrict = true, },
                new City { Id = 155, Description = "Paradise", IsActive = true, IsDistrict = true, },
                new City { Id = 156, Description = "Brisbane", IsActive = true, IsDistrict = true, },
                new City { Id = 157, Description = "Adelaide", IsActive = true, IsDistrict = true, },
                new City { Id = 158, Description = "Sydney", IsActive = true, IsDistrict = true, },
                new City { Id = 159, Description = "Alice Springs", IsActive = true, IsDistrict = true, },
                new City { Id = 160, Description = "Launceston", IsActive = true, IsDistrict = true, },
                new City { Id = 161, Description = "Perth", IsActive = true, IsDistrict = true, },
                new City { Id = 162, Description = "Baku", IsActive = true, IsDistrict = true, },
                new City { Id = 163, Description = "Dhaka", IsActive = true, IsDistrict = true, },
                new City { Id = 164, Description = "Chittagong", IsActive = true, IsDistrict = true, },
                new City { Id = 166, Description = "Cox's Bazar", IsActive = true, IsDistrict = true, },
                new City { Id = 167, Description = "Minsk", IsActive = true, IsDistrict = true, },
                new City { Id = 168, Description = "Belize City", IsActive = true, IsDistrict = true, },
                new City { Id = 169, Description = "Belmopan", IsActive = true, IsDistrict = true, },
                new City { Id = 170, Description = "Cotonou", IsActive = true, IsDistrict = true, },
                new City { Id = 171, Description = "Parakou", IsActive = true, IsDistrict = true, },
                new City { Id = 172, Description = "Possotome", IsActive = true, IsDistrict = true, },
                new City { Id = 173, Description = "Thimpu", IsActive = true, IsDistrict = true, },
                new City { Id = 174, Description = "Bumthang / Phuentsholing", IsActive = false, IsDistrict = true, },
                new City { Id = 175, Description = "Bumthang / Phuentsholing", IsActive = true, IsDistrict = true, },
                new City { Id = 176, Description = "Paro", IsActive = true, IsDistrict = true, },
                new City { Id = 177, Description = "Punakha", IsActive = true, IsDistrict = true, },
                new City { Id = 178, Description = "La Paz", IsActive = true, IsDistrict = true, },
                new City { Id = 179, Description = "Santa Cruz", IsActive = true, IsDistrict = true, },
                new City { Id = 180, Description = "Cochabamba", IsActive = true, IsDistrict = true, },
                new City { Id = 181, Description = "Potosi", IsActive = true, IsDistrict = true, },
                new City { Id = 182, Description = "Tarija", IsActive = true, IsDistrict = true, },
                new City { Id = 183, Description = "Oruro / Sucre / Cobija", IsActive = true, IsDistrict = true, },
                new City { Id = 184, Description = "Trini", IsActive = true, IsDistrict = true, },
                new City { Id = 185, Description = "Sarajevo", IsActive = true, IsDistrict = true, },
                new City { Id = 186, Description = "Gaborone", IsActive = true, IsDistrict = true, },
                new City { Id = 187, Description = "Maun", IsActive = true, IsDistrict = true, },
                new City { Id = 188, Description = "Francistown", IsActive = true, IsDistrict = true, },
                new City { Id = 189, Description = "Kasane", IsActive = true, IsDistrict = true, },
                new City { Id = 190, Description = "Palape", IsActive = true, IsDistrict = true, },
                new City { Id = 191, Description = "Selebe-Phikwe", IsActive = true, IsDistrict = true, },
                new City { Id = 192, Description = "Lobatse", IsActive = true, IsDistrict = true, },
                new City { Id = 193, Description = "Brazilia", IsActive = true, IsDistrict = true, },
                new City { Id = 194, Description = "Rio De Janeiro", IsActive = true, IsDistrict = true, },
                new City { Id = 195, Description = "Maccio", IsActive = true, IsDistrict = true, },
                new City { Id = 196, Description = "Aracaju / Recife / Alegre / Teresina", IsActive = true, IsDistrict = true, },
                new City { Id = 197, Description = "Natal", IsActive = true, IsDistrict = true, },
                new City { Id = 198, Description = "Porto", IsActive = true, IsDistrict = true, },
                new City { Id = 199, Description = "Sao Paulo", IsActive = true, IsDistrict = true, },
                new City { Id = 200, Description = "Teresina", IsActive = true, IsDistrict = true, },
                new City { Id = 201, Description = "Salvador", IsActive = true, IsDistrict = true, },
                new City { Id = 202, Description = "Curitiba", IsActive = true, IsDistrict = true, },
                new City { Id = 203, Description = "Manaus", IsActive = true, IsDistrict = true, },
                new City { Id = 204, Description = "Florianopolis", IsActive = true, IsDistrict = true, },
                new City { Id = 205, Description = "Belo Horizonte", IsActive = false, IsDistrict = true, },
                new City { Id = 206, Description = "Bandar Seri Bagawan", IsActive = true, IsDistrict = true, },
                new City { Id = 207, Description = "Sofia", IsActive = true, IsDistrict = true, },
                new City { Id = 208, Description = "Burgas / Plovdiv / Shumen", IsActive = true, IsDistrict = true, },
                new City { Id = 209, Description = "Sliven / Varna / Veliko Tamovo", IsActive = true, IsDistrict = true, },
                new City { Id = 210, Description = "Ouagadougou", IsActive = true, IsDistrict = true, },
                new City { Id = 211, Description = "Babo-Dioulasso", IsActive = true, IsDistrict = true, },
                new City { Id = 212, Description = "Banfora", IsActive = true, IsDistrict = true, },
                new City { Id = 213, Description = "Bujumbura", IsActive = true, IsDistrict = true, },
                new City { Id = 214, Description = "Phnom Penh", IsActive = false, IsDistrict = true, },
                new City { Id = 215, Description = "Siem Reap", IsActive = true, IsDistrict = true, },
                new City { Id = 216, Description = "Sihanouk Village", IsActive = true, IsDistrict = true, },
                new City { Id = 217, Description = "Phnom Penh", IsActive = true, IsDistrict = true, },
                new City { Id = 218, Description = "Yaounde", IsActive = true, IsDistrict = true, },
                new City { Id = 219, Description = "Douais", IsActive = true, IsDistrict = true, },
                new City { Id = 220, Description = "Berious", IsActive = true, IsDistrict = true, },
                new City { Id = 221, Description = "Bamenda", IsActive = true, IsDistrict = true, },
                new City { Id = 222, Description = "Kribi/ Limbe/ Edea / Buea", IsActive = true, IsDistrict = true, },
                new City { Id = 223, Description = "Ngaoundera", IsActive = true, IsDistrict = true, },
                new City { Id = 224, Description = "Maroua", IsActive = true, IsDistrict = true, },
                new City { Id = 225, Description = "Garoua", IsActive = true, IsDistrict = true, },
                new City { Id = 226, Description = "Ottawa", IsActive = true, IsDistrict = true, },
                new City { Id = 227, Description = "Toronto", IsActive = true, IsDistrict = true, },
                new City { Id = 228, Description = "Montreal", IsActive = true, IsDistrict = true, },
                new City { Id = 229, Description = "Vancouver", IsActive = true, IsDistrict = true, },
                new City { Id = 230, Description = "Quebec City", IsActive = true, IsDistrict = true, },
                new City { Id = 231, Description = "Calgary", IsActive = true, IsDistrict = true, },
                new City { Id = 232, Description = "Winnipeg", IsActive = true, IsDistrict = true, },
                new City { Id = 233, Description = "Prata", IsActive = true, IsDistrict = true, },
                new City { Id = 234, Description = "Santa Maria", IsActive = true, IsDistrict = true, },
                new City { Id = 235, Description = "Mindelo", IsActive = true, IsDistrict = true, },
                new City { Id = 236, Description = "Bangul", IsActive = true, IsDistrict = true, },
                new City { Id = 237, Description = "Bambari", IsActive = true, IsDistrict = true, },
                new City { Id = 238, Description = "Bouai", IsActive = true, IsDistrict = true, },
                new City { Id = 239, Description = "Ndjamena", IsActive = true, IsDistrict = true, },
                new City { Id = 240, Description = "Sarb", IsActive = true, IsDistrict = true, },
                new City { Id = 241, Description = "Campinas / Goiania / Joad Pessea", IsActive = true, IsDistrict = true, },
                new City { Id = 242, Description = "Campo / Grande / Belem", IsActive = true, IsDistrict = true, },
                new City { Id = 243, Description = "Moroni", IsActive = true, IsDistrict = true, },
                new City { Id = 244, Description = "Mutsamudu", IsActive = true, IsDistrict = true, },
                new City { Id = 245, Description = "Brazaaville", IsActive = true, IsDistrict = true, },
                new City { Id = 246, Description = "Pointe-Noire", IsActive = true, IsDistrict = true, },
                new City { Id = 247, Description = "Kinshasa", IsActive = true, IsDistrict = true, },
                new City { Id = 248, Description = "Mbuji-Mayi", IsActive = true, IsDistrict = true, },
                new City { Id = 249, Description = "Bukavu", IsActive = true, IsDistrict = true, },
                new City { Id = 250, Description = "Goma", IsActive = true, IsDistrict = true, },
                new City { Id = 251, Description = "Uvira", IsActive = true, IsDistrict = true, },
                new City { Id = 252, Description = "Lubumbashi", IsActive = true, IsDistrict = true, },
                new City { Id = 253, Description = "Shaba", IsActive = true, IsDistrict = true, },
                new City { Id = 254, Description = "Rarotonga", IsActive = true, IsDistrict = true, },
                new City { Id = 255, Description = "Aiiutaki", IsActive = true, IsDistrict = true, },
                new City { Id = 256, Description = "Aitu", IsActive = true, IsDistrict = true, },
                new City { Id = 257, Description = "Liberia", IsActive = true, IsDistrict = true, },
                new City { Id = 258, Description = "Puntaremas City", IsActive = true, IsDistrict = true, },
                new City { Id = 259, Description = "Limon City", IsActive = true, IsDistrict = true, },
                new City { Id = 260, Description = "Guanacaste", IsActive = true, IsDistrict = true, },
                new City { Id = 261, Description = "San Jose", IsActive = true, IsDistrict = true, },
                new City { Id = 262, Description = "Abidjan", IsActive = true, IsDistrict = true, },
                new City { Id = 263, Description = "Yomoussokro", IsActive = true, IsDistrict = true, },
                new City { Id = 264, Description = "Bouake", IsActive = true, IsDistrict = true, },
                new City { Id = 265, Description = "San Pedro", IsActive = true, IsDistrict = true, },
                new City { Id = 266, Description = "Zareb", IsActive = true, IsDistrict = true, },
                new City { Id = 267, Description = "Dubrovnik", IsActive = true, IsDistrict = true, },
                new City { Id = 268, Description = "Havana", IsActive = true, IsDistrict = true, },
                new City { Id = 269, Description = "Santiago-De-Cuba", IsActive = true, IsDistrict = true, },
                new City { Id = 270, Description = "Nicosia", IsActive = true, IsDistrict = true, },
                new City { Id = 271, Description = "Prague", IsActive = true, IsDistrict = true, },
                new City { Id = 272, Description = "Karloyy Vary", IsActive = true, IsDistrict = true, },
                new City { Id = 273, Description = "Brno", IsActive = true, IsDistrict = true, },
                new City { Id = 274, Description = "Plzen", IsActive = true, IsDistrict = true, },
                new City { Id = 275, Description = "Hradec Kralove", IsActive = true, IsDistrict = true, },
                new City { Id = 276, Description = "Ceske Budejovice", IsActive = true, IsDistrict = true, },
                new City { Id = 277, Description = "Djibouti", IsActive = true, IsDistrict = true, },
                new City { Id = 278, Description = "Tadjourah", IsActive = true, IsDistrict = true, },
                new City { Id = 279, Description = "Santo Domingo", IsActive = true, IsDistrict = true, },
                new City { Id = 280, Description = "La Romana", IsActive = true, IsDistrict = true, },
                new City { Id = 281, Description = "Puerto Plata", IsActive = true, IsDistrict = true, },
                new City { Id = 282, Description = "Samana", IsActive = true, IsDistrict = true, },
                new City { Id = 283, Description = "Santiago", IsActive = true, IsDistrict = true, },
                new City { Id = 284, Description = "Quito", IsActive = true, IsDistrict = true, },
                new City { Id = 285, Description = "Guayaquil", IsActive = true, IsDistrict = true, },
                new City { Id = 286, Description = "Cuenca", IsActive = true, IsDistrict = true, },
                new City { Id = 287, Description = "Cairo", IsActive = true, IsDistrict = true, },
                new City { Id = 288, Description = "Alexandria", IsActive = true, IsDistrict = true, },
                new City { Id = 289, Description = "Sharm El Sheikh", IsActive = true, IsDistrict = true, },
                new City { Id = 290, Description = "Luxor", IsActive = true, IsDistrict = true, },
                new City { Id = 291, Description = "San Salvador", IsActive = true, IsDistrict = true, },
                new City { Id = 292, Description = "San Miquel", IsActive = true, IsDistrict = true, },
                new City { Id = 293, Description = "Malabo", IsActive = true, IsDistrict = true, },
                new City { Id = 294, Description = "Bata", IsActive = true, IsDistrict = true, },
                new City { Id = 295, Description = "Asmara", IsActive = true, IsDistrict = true, },
                new City { Id = 296, Description = "Assab", IsActive = true, IsDistrict = true, },
                new City { Id = 297, Description = "Massawa", IsActive = true, IsDistrict = true, },
                new City { Id = 298, Description = "Keren", IsActive = true, IsDistrict = true, },
                new City { Id = 299, Description = "Tallin", IsActive = true, IsDistrict = true, },
                new City { Id = 300, Description = "Parnu", IsActive = true, IsDistrict = true, },
                new City { Id = 301, Description = "Tartu", IsActive = true, IsDistrict = true, },
                new City { Id = 302, Description = "Addis Ababa", IsActive = true, IsDistrict = true, },
                new City { Id = 303, Description = "Suva", IsActive = true, IsDistrict = true, },
                new City { Id = 304, Description = "Nadi", IsActive = true, IsDistrict = true, },
                new City { Id = 305, Description = "Helsinki", IsActive = true, IsDistrict = true, },
                new City { Id = 306, Description = "Paris", IsActive = true, IsDistrict = true, },
                new City { Id = 307, Description = "Cayenne", IsActive = true, IsDistrict = true, },
                new City { Id = 308, Description = "Libreville", IsActive = true, IsDistrict = true, },
                new City { Id = 309, Description = "Port Gentil", IsActive = true, IsDistrict = true, },
                new City { Id = 310, Description = "Lambarene", IsActive = true, IsDistrict = true, },
                new City { Id = 311, Description = "Franceville", IsActive = true, IsDistrict = true, },
                new City { Id = 312, Description = "Banjul", IsActive = true, IsDistrict = true, },
                new City { Id = 313, Description = "Tbilisi", IsActive = true, IsDistrict = true, },
                new City { Id = 314, Description = "Berlin", IsActive = true, IsDistrict = true, },
                new City { Id = 315, Description = "Frankfurt", IsActive = true, IsDistrict = true, },
                new City { Id = 316, Description = "Bonn", IsActive = true, IsDistrict = true, },
                new City { Id = 317, Description = "Leipzig", IsActive = true, IsDistrict = true, },
                new City { Id = 318, Description = "Accra", IsActive = true, IsDistrict = true, },
                new City { Id = 319, Description = "Akesombo", IsActive = true, IsDistrict = true, },
                new City { Id = 320, Description = "Kumasi", IsActive = true, IsDistrict = true, },
                new City { Id = 321, Description = "Takoradi", IsActive = true, IsDistrict = true, },
                new City { Id = 322, Description = "Tamale", IsActive = true, IsDistrict = true, },
                new City { Id = 323, Description = "Athens", IsActive = true, IsDistrict = true, },
                new City { Id = 324, Description = "Guatemala City", IsActive = true, IsDistrict = true, },
                new City { Id = 325, Description = "Antigua", IsActive = true, IsDistrict = true, },
                new City { Id = 326, Description = "", IsActive = true, IsDistrict = true, },
                new City { Id = 327, Description = "Panajachel", IsActive = true, IsDistrict = true, },
                new City { Id = 328, Description = "Conakry", IsActive = true, IsDistrict = true, },
                new City { Id = 329, Description = "Nzerekore", IsActive = true, IsDistrict = true, },
                new City { Id = 330, Description = "Kamsar", IsActive = true, IsDistrict = true, },
                new City { Id = 331, Description = "Mamou", IsActive = true, IsDistrict = true, },
                new City { Id = 332, Description = "Fria", IsActive = true, IsDistrict = true, },
                new City { Id = 333, Description = "Labe", IsActive = true, IsDistrict = true, },
                new City { Id = 334, Description = "Dubreka", IsActive = true, IsDistrict = true, },
                new City { Id = 335, Description = "Kindia", IsActive = true, IsDistrict = true, },
                new City { Id = 336, Description = "Bissau", IsActive = true, IsDistrict = true, },
                new City { Id = 337, Description = "Bubaque", IsActive = true, IsDistrict = true, },
                new City { Id = 338, Description = "Bafata", IsActive = true, IsDistrict = true, },
                new City { Id = 339, Description = "Georgetown", IsActive = true, IsDistrict = true, },
                new City { Id = 340, Description = "Linden", IsActive = true, IsDistrict = true, },
                new City { Id = 341, Description = "New Amsterdam", IsActive = true, IsDistrict = true, },
                new City { Id = 342, Description = "Portau-Prince", IsActive = true, IsDistrict = true, },
                new City { Id = 343, Description = "Tegucigalpa", IsActive = true, IsDistrict = true, },
                new City { Id = 344, Description = "San Pedro Sula", IsActive = true, IsDistrict = true, },
                new City { Id = 345, Description = "Roatan Island", IsActive = true, IsDistrict = true, },
                new City { Id = 346, Description = "New Delhi", IsActive = true, IsDistrict = true, },
                new City { Id = 347, Description = "Hyderabad", IsActive = true, IsDistrict = true, },
                new City { Id = 348, Description = "Calcutta", IsActive = true, IsDistrict = true, },
                new City { Id = 349, Description = "Membai (Bombay)", IsActive = true, IsDistrict = true, },
                new City { Id = 350, Description = "Bangalore", IsActive = true, IsDistrict = true, },
                new City { Id = 351, Description = "Chennai (Madras)", IsActive = true, IsDistrict = true, },
                new City { Id = 352, Description = "Agra", IsActive = true, IsDistrict = true, },
                new City { Id = 353, Description = "Mysore", IsActive = true, IsDistrict = true, },
                new City { Id = 354, Description = "Udaipur", IsActive = true, IsDistrict = true, },
                new City { Id = 355, Description = "Goa", IsActive = true, IsDistrict = true, },
                new City { Id = 356, Description = "Lucknow", IsActive = true, IsDistrict = true, },
                new City { Id = 357, Description = "Jaipur", IsActive = true, IsDistrict = true, },
                new City { Id = 358, Description = "Varanasi", IsActive = true, IsDistrict = true, },
                new City { Id = 359, Description = "Aurangaabad", IsActive = true, IsDistrict = true, },
                new City { Id = 360, Description = "Shimla", IsActive = true, IsDistrict = true, },
                new City { Id = 361, Description = "Jakrta", IsActive = true, IsDistrict = true, },
                new City { Id = 362, Description = "Mataram", IsActive = true, IsDistrict = true, },
                new City { Id = 363, Description = "Bali Island", IsActive = true, IsDistrict = true, },
                new City { Id = 364, Description = "Surabaya", IsActive = true, IsDistrict = true, },
                new City { Id = 365, Description = "Batam Island", IsActive = true, IsDistrict = true, },
                new City { Id = 366, Description = "Bandar Lampung", IsActive = true, IsDistrict = true, },
                new City { Id = 367, Description = "Semarang", IsActive = true, IsDistrict = true, },
                new City { Id = 368, Description = "Medan", IsActive = true, IsDistrict = true, },
                new City { Id = 369, Description = "Yogyakarta", IsActive = true, IsDistrict = true, },
                new City { Id = 370, Description = "Menado", IsActive = true, IsDistrict = true, },
                new City { Id = 371, Description = "Solo", IsActive = true, IsDistrict = true, },
                new City { Id = 372, Description = "Bandung", IsActive = true, IsDistrict = true, },
                new City { Id = 373, Description = "Bogor", IsActive = true, IsDistrict = true, },
                new City { Id = 374, Description = "Jayapura", IsActive = true, IsDistrict = true, },
                new City { Id = 375, Description = "Malang", IsActive = true, IsDistrict = true, },
                new City { Id = 376, Description = "Kupang", IsActive = true, IsDistrict = true, },
                new City { Id = 377, Description = "Bengkula", IsActive = true, IsDistrict = true, },
                new City { Id = 378, Description = "Ujang Pandang", IsActive = true, IsDistrict = true, },
                new City { Id = 379, Description = "Palembang", IsActive = true, IsDistrict = true, },
                new City { Id = 380, Description = "Banjarmansin", IsActive = true, IsDistrict = true, },
                new City { Id = 381, Description = "Tanjung Pinang", IsActive = true, IsDistrict = true, },
                new City { Id = 382, Description = "Ambon", IsActive = true, IsDistrict = true, },
                new City { Id = 383, Description = "Baghdad", IsActive = true, IsDistrict = true, },
                new City { Id = 384, Description = "Rome", IsActive = true, IsDistrict = true, },
                new City { Id = 385, Description = "Milan", IsActive = true, IsDistrict = true, },
                new City { Id = 386, Description = "Venice", IsActive = true, IsDistrict = true, },
                new City { Id = 387, Description = "Florence", IsActive = true, IsDistrict = true, },
                new City { Id = 388, Description = "Kigston", IsActive = true, IsDistrict = true, },
                new City { Id = 389, Description = "Tokyo", IsActive = true, IsDistrict = true, },
                new City { Id = 390, Description = "Osaka", IsActive = true, IsDistrict = true, },
                new City { Id = 391, Description = "Kyoto", IsActive = true, IsDistrict = true, },
                new City { Id = 392, Description = "Yokohama", IsActive = true, IsDistrict = true, },
                new City { Id = 393, Description = "Okinawa", IsActive = true, IsDistrict = true, },
                new City { Id = 394, Description = "Kobe", IsActive = true, IsDistrict = true, },
                new City { Id = 395, Description = "Nogoya", IsActive = true, IsDistrict = true, },
                new City { Id = 396, Description = "Hiroshima", IsActive = true, IsDistrict = true, },
                new City { Id = 397, Description = "Hakone", IsActive = true, IsDistrict = true, },
                new City { Id = 398, Description = "Shimoda", IsActive = true, IsDistrict = true, },
                new City { Id = 399, Description = "Furano", IsActive = true, IsDistrict = true, },
                new City { Id = 400, Description = "Shodoshima", IsActive = true, IsDistrict = true, },
                new City { Id = 401, Description = "Hakata", IsActive = true, IsDistrict = true, },
                new City { Id = 402, Description = "Sapporro", IsActive = true, IsDistrict = true, },
                new City { Id = 403, Description = "Nara", IsActive = true, IsDistrict = true, },
                new City { Id = 404, Description = "Tsuruoa", IsActive = true, IsDistrict = true, },
                new City { Id = 405, Description = "Miyazaki", IsActive = true, IsDistrict = true, },
                new City { Id = 406, Description = "Kokowue/ Kanazwa/ Karatsu", IsActive = true, IsDistrict = true, },
                new City { Id = 407, Description = "Saga/ Nagasaki/ Narita", IsActive = true, IsDistrict = true, },
                new City { Id = 408, Description = "Chitose", IsActive = true, IsDistrict = true, },
                new City { Id = 409, Description = "Kawasaki", IsActive = true, IsDistrict = true, },
                new City { Id = 410, Description = "Sendaicity", IsActive = true, IsDistrict = true, },
                new City { Id = 411, Description = "Okayama", IsActive = true, IsDistrict = true, },
                new City { Id = 412, Description = "Shizuuk City", IsActive = true, IsDistrict = true, },
                new City { Id = 413, Description = "Matsuyama", IsActive = true, IsDistrict = true, },
                new City { Id = 414, Description = "Amman", IsActive = true, IsDistrict = true, },
                new City { Id = 415, Description = "Jerusalem", IsActive = true, IsDistrict = true, },
                new City { Id = 416, Description = "Aqaba", IsActive = true, IsDistrict = true, },
                new City { Id = 417, Description = "Astana", IsActive = true, IsDistrict = true, },
                new City { Id = 418, Description = "Alma Ata", IsActive = true, IsDistrict = true, },
                new City { Id = 419, Description = "Nairobi", IsActive = true, IsDistrict = true, },
                new City { Id = 420, Description = "Lamu", IsActive = true, IsDistrict = true, },
                new City { Id = 421, Description = "Mombasa", IsActive = true, IsDistrict = true, },
                new City { Id = 422, Description = "Naivasha", IsActive = true, IsDistrict = true, },
                new City { Id = 423, Description = "Baringo & Nyeri", IsActive = true, IsDistrict = true, },
                new City { Id = 424, Description = "Kiribati/ Christmas Island", IsActive = true, IsDistrict = true, },
                new City { Id = 425, Description = "Outer Island", IsActive = true, IsDistrict = true, },
                new City { Id = 426, Description = "Pyongyang", IsActive = true, IsDistrict = true, },
                new City { Id = 427, Description = "Seoul", IsActive = true, IsDistrict = true, },
                new City { Id = 428, Description = "Cheju Island", IsActive = true, IsDistrict = true, },
                new City { Id = 429, Description = "Pusan", IsActive = true, IsDistrict = true, },
                new City { Id = 430, Description = "Kyugijv", IsActive = true, IsDistrict = true, },
                new City { Id = 431, Description = "Daejon", IsActive = true, IsDistrict = true, },
                new City { Id = 432, Description = "Changwon & Yousong", IsActive = true, IsDistrict = true, },
                new City { Id = 433, Description = "Bishkek", IsActive = true, IsDistrict = true, },
                new City { Id = 434, Description = "Vientiane", IsActive = true, IsDistrict = true, },
                new City { Id = 435, Description = "Bokeo/ Oudomxay/ Thakhaek", IsActive = true, IsDistrict = true, },
                new City { Id = 436, Description = "Luang Prabang", IsActive = true, IsDistrict = true, },
                new City { Id = 437, Description = "Pakse", IsActive = true, IsDistrict = true, },
                new City { Id = 438, Description = "Savannakhet", IsActive = true, IsDistrict = true, },
                new City { Id = 439, Description = "Phonsavanh", IsActive = true, IsDistrict = true, },
                new City { Id = 440, Description = "Riga", IsActive = true, IsDistrict = true, },
                new City { Id = 441, Description = "Greater Beirut", IsActive = true, IsDistrict = true, },
                new City { Id = 442, Description = "Al Metn", IsActive = true, IsDistrict = true, },
                new City { Id = 443, Description = "Bekka/ Baalbeck", IsActive = true, IsDistrict = true, },
                new City { Id = 444, Description = "Beeka/ Chitaura", IsActive = true, IsDistrict = true, },
                new City { Id = 445, Description = "Jounieh", IsActive = true, IsDistrict = true, },
                new City { Id = 446, Description = "Khayzaran/ Tyr", IsActive = true, IsDistrict = true, },
                new City { Id = 447, Description = "Tripoli", IsActive = true, IsDistrict = true, },
                new City { Id = 448, Description = "Maseru", IsActive = true, IsDistrict = true, },
                new City { Id = 449, Description = "Monrovia", IsActive = true, IsDistrict = true, },
                new City { Id = 450, Description = "Tripoli", IsActive = true, IsDistrict = true, },
                new City { Id = 451, Description = "Benghazi/ Sirte/ Misurate", IsActive = true, IsDistrict = true, },
                new City { Id = 452, Description = "Vilinius", IsActive = true, IsDistrict = true, },
                new City { Id = 453, Description = "Skopje", IsActive = true, IsDistrict = true, },
                new City { Id = 455, Description = "Antsirabe", IsActive = true, IsDistrict = true, },
                new City { Id = 456, Description = "Diego Suerez", IsActive = true, IsDistrict = true, },
                new City { Id = 457, Description = "Fort Dauphin", IsActive = true, IsDistrict = true, },
                new City { Id = 458, Description = "Tulear", IsActive = true, IsDistrict = true, },
                new City { Id = 459, Description = "Fianarantsoa", IsActive = true, IsDistrict = true, },
                new City { Id = 460, Description = "Mahajanga", IsActive = true, IsDistrict = true, },
                new City { Id = 461, Description = "Antsiranana", IsActive = true, IsDistrict = true, },
                new City { Id = 462, Description = "Morondave/ Toliary", IsActive = true, IsDistrict = true, },
                new City { Id = 463, Description = "Nosy-Be", IsActive = true, IsDistrict = true, },
                new City { Id = 464, Description = "Toamasina", IsActive = true, IsDistrict = true, },
                new City { Id = 465, Description = "Tolagnaro", IsActive = true, IsDistrict = true, },
                new City { Id = 466, Description = "Antananariov", IsActive = true, IsDistrict = true, },
                new City { Id = 467, Description = "Lilongwe", IsActive = true, IsDistrict = true, },
                new City { Id = 468, Description = "Blantyre", IsActive = true, IsDistrict = true, },
                new City { Id = 469, Description = "Mangochi", IsActive = true, IsDistrict = true, },
                new City { Id = 470, Description = "Mzuzu", IsActive = true, IsDistrict = true, },
                new City { Id = 471, Description = "Salima", IsActive = true, IsDistrict = true, },
                new City { Id = 472, Description = "Zomba", IsActive = true, IsDistrict = true, },
                new City { Id = 473, Description = "Kuala Lumpur", IsActive = true, IsDistrict = true, },
                new City { Id = 474, Description = "Kota Kinabalu", IsActive = true, IsDistrict = true, },
                new City { Id = 475, Description = "Langkawi", IsActive = true, IsDistrict = true, },
                new City { Id = 476, Description = "Penang", IsActive = true, IsDistrict = true, },
                new City { Id = 477, Description = "Putra Jaya", IsActive = true, IsDistrict = true, },
                new City { Id = 478, Description = "Male", IsActive = true, IsDistrict = true, },
                new City { Id = 479, Description = "Bemako", IsActive = true, IsDistrict = true, },
                new City { Id = 480, Description = "Timbuctou/ Mopati", IsActive = true, IsDistrict = true, },
                new City { Id = 481, Description = "Nouakchott", IsActive = true, IsDistrict = true, },
                new City { Id = 482, Description = "Nouadhidou", IsActive = true, IsDistrict = true, },
                new City { Id = 483, Description = "Zouerate", IsActive = true, IsDistrict = true, },
                new City { Id = 484, Description = "UNDP base in Kaedi", IsActive = true, IsDistrict = true, },
                new City { Id = 485, Description = "Kiffa base", IsActive = true, IsDistrict = true, },
                new City { Id = 486, Description = "Rosso", IsActive = true, IsDistrict = true, },
                new City { Id = 487, Description = "Port Louis / Mauritius", IsActive = true, IsDistrict = true, },
                new City { Id = 488, Description = "Mexico City", IsActive = true, IsDistrict = true, },
                new City { Id = 489, Description = "Manzanillo/ Colima", IsActive = true, IsDistrict = true, },
                new City { Id = 490, Description = "Cancun/ Quintana Roo", IsActive = true, IsDistrict = true, },
                new City { Id = 491, Description = "Ixtapa/ Guerrero", IsActive = true, IsDistrict = true, },
                new City { Id = 492, Description = "Acapulco/ Guerrero", IsActive = true, IsDistrict = true, },
                new City { Id = 493, Description = "Aguscalientes", IsActive = true, IsDistrict = true, },
                new City { Id = 494, Description = "Ciudad Juarez/ Chihuahua", IsActive = true, IsDistrict = true, },
                new City { Id = 495, Description = "Coatzacoalcos/ Veracrus", IsActive = true, IsDistrict = true, },
                new City { Id = 496, Description = "Cocoyoc/ Morelos", IsActive = true, IsDistrict = true, },
                new City { Id = 497, Description = "Culiacan/ Sinaloa", IsActive = true, IsDistrict = true, },
                new City { Id = 498, Description = "Durango", IsActive = true, IsDistrict = true, },
                new City { Id = 499, Description = "Guadalajara/ Jalisco", IsActive = true, IsDistrict = true, },
                new City { Id = 500, Description = "Guanajuato", IsActive = true, IsDistrict = true, },
                new City { Id = 501, Description = "Hemosillo/ Sonora", IsActive = true, IsDistrict = true, },
                new City { Id = 502, Description = "Leon/ Guanjuato", IsActive = true, IsDistrict = true, },
                new City { Id = 503, Description = "Mazatlan/ Sinaloa", IsActive = true, IsDistrict = true, },
                new City { Id = 504, Description = "Merida/ Yucatan", IsActive = true, IsDistrict = true, },
                new City { Id = 505, Description = "Mexicali/ Baja Claifornia Norte", IsActive = true, IsDistrict = true, },
                new City { Id = 506, Description = "Monterrey/ Nuevo Leon", IsActive = true, IsDistrict = true, },
                new City { Id = 507, Description = "Morelia/ Michoacan", IsActive = true, IsDistrict = true, },
                new City { Id = 508, Description = "Oaxaca", IsActive = true, IsDistrict = true, },
                new City { Id = 509, Description = "Pachuca, Hidalgo", IsActive = false, IsDistrict = true, },
                new City { Id = 510, Description = "Puebla/ Puebla", IsActive = true, IsDistrict = true, },
                new City { Id = 511, Description = "Puerto Vallarta/ Jalisco", IsActive = true, IsDistrict = true, },
                new City { Id = 512, Description = "Queretaro/ Queretaro", IsActive = true, IsDistrict = true, },
                new City { Id = 513, Description = "Saltillo/ Cohauila", IsActive = true, IsDistrict = true, },
                new City { Id = 514, Description = "San Luis Potosi/ San Luis Potosi", IsActive = true, IsDistrict = true, },
                new City { Id = 515, Description = "Tapahula/ Chiapas", IsActive = true, IsDistrict = true, },
                new City { Id = 516, Description = "Baja California Norte", IsActive = true, IsDistrict = true, },
                new City { Id = 517, Description = "Tiaxcala/ Tiaxcala", IsActive = true, IsDistrict = true, },
                new City { Id = 518, Description = "Toluca Edo de Mexico", IsActive = true, IsDistrict = true, },
                new City { Id = 519, Description = "Torreon/ Coahuila", IsActive = true, IsDistrict = true, },
                new City { Id = 520, Description = "Tuxtla/ Gutierrez", IsActive = true, IsDistrict = true, },
                new City { Id = 521, Description = "Beracnz/ Veracruz", IsActive = true, IsDistrict = true, },
                new City { Id = 522, Description = "Villahermosa/ Tabasco", IsActive = true, IsDistrict = true, },
                new City { Id = 523, Description = "Zacatecas/ Zacatecas", IsActive = true, IsDistrict = true, },
                new City { Id = 524, Description = "Cozumel/ Quintana Roo", IsActive = true, IsDistrict = true, },
                new City { Id = 525, Description = "Cuerravaca/ Morelos", IsActive = true, IsDistrict = true, },
                new City { Id = 526, Description = "CAbo San Lucas/ Baja California Sur", IsActive = true, IsDistrict = true, },
                new City { Id = 527, Description = "Loreto/ Haja/ California Sur", IsActive = true, IsDistrict = true, },
                new City { Id = 528, Description = "San Cristobal De la Casas/ Chiapas", IsActive = true, IsDistrict = true, },
                new City { Id = 529, Description = "Campeche/ Campeche Neuvo Laredo/ Tamaulipas Merida", IsActive = true, IsDistrict = true, },
                new City { Id = 530, Description = "Matamoros/ Tamulipas", IsActive = true, IsDistrict = true, },
                new City { Id = 531, Description = "Tepic/ Niarjarit", IsActive = true, IsDistrict = true, },
                new City { Id = 532, Description = "Nogales/ Sonora", IsActive = true, IsDistrict = true, },
                new City { Id = 533, Description = "Chetumal/ Quinta Too", IsActive = true, IsDistrict = true, },
                new City { Id = 534, Description = "Reynosa/ Tamaulipas Comitan, Chiapas", IsActive = true, IsDistrict = true, },
                new City { Id = 535, Description = "Ensenda Baja", IsActive = true, IsDistrict = true, },
                new City { Id = 536, Description = "Kishinev", IsActive = true, IsDistrict = true, },
                new City { Id = 537, Description = "Ulan Bater", IsActive = true, IsDistrict = true, },
                new City { Id = 538, Description = "Rabat", IsActive = true, IsDistrict = true, },
                new City { Id = 539, Description = "Agadir", IsActive = true, IsDistrict = true, },
                new City { Id = 540, Description = "Casablanca", IsActive = true, IsDistrict = true, },
                new City { Id = 541, Description = "Fes", IsActive = true, IsDistrict = true, },
                new City { Id = 542, Description = "Laayoune", IsActive = true, IsDistrict = true, },
                new City { Id = 543, Description = "Marrakech", IsActive = true, IsDistrict = true, },
                new City { Id = 544, Description = "Quarzazate", IsActive = true, IsDistrict = true, },
                new City { Id = 545, Description = "Tangiers", IsActive = true, IsDistrict = true, },
                new City { Id = 546, Description = "Maputo", IsActive = true, IsDistrict = true, },
                new City { Id = 547, Description = "Beira/ Sofala", IsActive = true, IsDistrict = true, },
                new City { Id = 548, Description = "Chimoio/  Manica", IsActive = true, IsDistrict = true, },
                new City { Id = 549, Description = "Nampula", IsActive = true, IsDistrict = true, },
                new City { Id = 550, Description = "Pmba/ Coba Delgado", IsActive = true, IsDistrict = true, },
                new City { Id = 551, Description = "Quelimane/ Niassa Zambezia Lilchinga", IsActive = true, IsDistrict = true, },
                new City { Id = 552, Description = "Yangoon/ Nay Pye Taiw", IsActive = true, IsDistrict = true, },
                new City { Id = 553, Description = "Sandoway", IsActive = true, IsDistrict = true, },
                new City { Id = 554, Description = "Maymo", IsActive = true, IsDistrict = true, },
                new City { Id = 555, Description = "Lashio", IsActive = true, IsDistrict = true, },
                new City { Id = 556, Description = "Pagan", IsActive = true, IsDistrict = true, },
                new City { Id = 557, Description = "Kentung", IsActive = true, IsDistrict = true, },
                new City { Id = 558, Description = "Kyaing Tong", IsActive = true, IsDistrict = true, },
                new City { Id = 559, Description = "Taunggyi", IsActive = true, IsDistrict = true, },
                new City { Id = 560, Description = "Mandalay", IsActive = true, IsDistrict = true, },
                new City { Id = 561, Description = "Windhoek", IsActive = true, IsDistrict = true, },
                new City { Id = 562, Description = "Luderitz/ Otavi", IsActive = true, IsDistrict = true, },
                new City { Id = 563, Description = "Grootfontein", IsActive = true, IsDistrict = true, },
                new City { Id = 564, Description = "Karasburg", IsActive = true, IsDistrict = true, },
                new City { Id = 565, Description = "Kantima Mulilo/ Maltahole", IsActive = true, IsDistrict = true, },
                new City { Id = 566, Description = "Keetmanshoop", IsActive = true, IsDistrict = true, },
                new City { Id = 567, Description = "Omaruru", IsActive = true, IsDistrict = true, },
                new City { Id = 568, Description = "Ondangwa", IsActive = true, IsDistrict = true, },
                new City { Id = 569, Description = "Opuwo", IsActive = true, IsDistrict = true, },
                new City { Id = 570, Description = "Oshakati", IsActive = true, IsDistrict = true, },
                new City { Id = 571, Description = "Otjiwarongo", IsActive = true, IsDistrict = true, },
                new City { Id = 572, Description = "Swakopmund", IsActive = true, IsDistrict = true, },
                new City { Id = 573, Description = "Walvis Bay", IsActive = true, IsDistrict = true, },
                new City { Id = 574, Description = "Katmandu", IsActive = true, IsDistrict = true, },
                new City { Id = 575, Description = "Nepalgunj", IsActive = true, IsDistrict = true, },
                new City { Id = 576, Description = "Pokhara", IsActive = true, IsDistrict = true, },
                new City { Id = 577, Description = "Aruba (15 April to 15 December)", IsActive = true, IsDistrict = true, },
                new City { Id = 578, Description = "St. Eustasius (15 April to 15 December)", IsActive = true, IsDistrict = true, },
                new City { Id = 579, Description = "St. Maarten (15 April to 15 December)", IsActive = true, IsDistrict = true, },
                new City { Id = 580, Description = "Curacao (15 April to 15 December)", IsActive = true, IsDistrict = true, },
                new City { Id = 581, Description = "Bonaire (15 April to 15 December)", IsActive = true, IsDistrict = true, },
                new City { Id = 582, Description = "Saba ((15 April to 15 December)", IsActive = true, IsDistrict = true, },
                new City { Id = 583, Description = "Aruba (16 Dec to 14 April)", IsActive = true, IsDistrict = true, },
                new City { Id = 584, Description = "St. Eustasius ((16 Dec to 14 April)", IsActive = true, IsDistrict = true, },
                new City { Id = 585, Description = "st Maarten (16 Dec to 14 April)", IsActive = true, IsDistrict = true, },
                new City { Id = 586, Description = "Curacao (16 Dec to 14 April)", IsActive = true, IsDistrict = true, },
                new City { Id = 587, Description = "Bonaire (16 Dec to 14 April)", IsActive = true, IsDistrict = true, },
                new City { Id = 588, Description = "Saba (16 Dec to 14 April)", IsActive = true, IsDistrict = true, },
                new City { Id = 589, Description = "Wellington/ Auckland/ Christchurch", IsActive = true, IsDistrict = true, },
                new City { Id = 590, Description = "Managua", IsActive = true, IsDistrict = true, },
                new City { Id = 591, Description = "Niamey", IsActive = true, IsDistrict = true, },
                new City { Id = 592, Description = "Agadez", IsActive = true, IsDistrict = true, },
                new City { Id = 593, Description = "Maradi", IsActive = true, IsDistrict = true, },
                new City { Id = 594, Description = "Abuja", IsActive = true, IsDistrict = true, },
                new City { Id = 595, Description = "Lagos", IsActive = true, IsDistrict = true, },
                new City { Id = 596, Description = "Port Harcourt", IsActive = true, IsDistrict = true, },
                new City { Id = 597, Description = "Ota", IsActive = true, IsDistrict = true, },
                new City { Id = 598, Description = "Katsina", IsActive = true, IsDistrict = true, },
                new City { Id = 599, Description = "Ibadan", IsActive = true, IsDistrict = true, },
                new City { Id = 600, Description = "Kano", IsActive = true, IsDistrict = true, },
                new City { Id = 601, Description = "Maiduguri", IsActive = true, IsDistrict = true, },
                new City { Id = 602, Description = "Sokoto", IsActive = true, IsDistrict = true, },
                new City { Id = 603, Description = "Yola", IsActive = true, IsDistrict = true, },
                new City { Id = 604, Description = "Minna", IsActive = true, IsDistrict = true, },
                new City { Id = 605, Description = "UNDP Guest House Lagos", IsActive = true, IsDistrict = true, },
                new City { Id = 606, Description = "Kaduna", IsActive = true, IsDistrict = true, },
                new City { Id = 607, Description = "Ilorin", IsActive = true, IsDistrict = true, },
                new City { Id = 608, Description = "Enugu", IsActive = true, IsDistrict = true, },
                new City { Id = 609, Description = "Ijebu-Ode", IsActive = true, IsDistrict = true, },
                new City { Id = 610, Description = "Benin City", IsActive = true, IsDistrict = true, },
                new City { Id = 611, Description = "Baunchi", IsActive = true, IsDistrict = true, },
                new City { Id = 612, Description = "Jos", IsActive = true, IsDistrict = true, },
                new City { Id = 613, Description = "Owerri", IsActive = true, IsDistrict = true, },
                new City { Id = 614, Description = "Makurdi", IsActive = true, IsDistrict = true, },
                new City { Id = 615, Description = "Calabar", IsActive = true, IsDistrict = true, },
                new City { Id = 616, Description = "Abeokuta", IsActive = true, IsDistrict = true, },
                new City { Id = 617, Description = "Muscat", IsActive = true, IsDistrict = true, },
                new City { Id = 618, Description = "Salalah", IsActive = true, IsDistrict = true, },
                new City { Id = 619, Description = "Nizwa", IsActive = true, IsDistrict = true, },
                new City { Id = 620, Description = "Bambito", IsActive = true, IsDistrict = true, },
                new City { Id = 621, Description = "Pnama City", IsActive = true, IsDistrict = true, },
                new City { Id = 622, Description = "Colon", IsActive = true, IsDistrict = true, },
                new City { Id = 623, Description = "Contadora Island", IsActive = true, IsDistrict = true, },
                new City { Id = 624, Description = "Port Moresby", IsActive = true, IsDistrict = true, },
                new City { Id = 625, Description = "Alotau", IsActive = true, IsDistrict = true, },
                new City { Id = 626, Description = "Buka", IsActive = true, IsDistrict = true, },
                new City { Id = 627, Description = "Bulolo", IsActive = true, IsDistrict = true, },
                new City { Id = 628, Description = "Daru", IsActive = true, IsDistrict = true, },
                new City { Id = 629, Description = "Goroka", IsActive = true, IsDistrict = true, },
                new City { Id = 630, Description = "Kainantu", IsActive = true, IsDistrict = true, },
                new City { Id = 631, Description = "Kavieng", IsActive = true, IsDistrict = true, },
                new City { Id = 632, Description = "Kimbe", IsActive = true, IsDistrict = true, },
                new City { Id = 633, Description = "Kinuga", IsActive = true, IsDistrict = true, },
                new City { Id = 634, Description = "Kundiawa", IsActive = true, IsDistrict = true, },
                new City { Id = 635, Description = "Lae", IsActive = true, IsDistrict = true, },
                new City { Id = 636, Description = "Lorengau", IsActive = true, IsDistrict = true, },
                new City { Id = 637, Description = "Madang", IsActive = true, IsDistrict = true, },
                new City { Id = 638, Description = "Mendi", IsActive = true, IsDistrict = true, },
                new City { Id = 639, Description = "Minj", IsActive = true, IsDistrict = true, },
                new City { Id = 640, Description = "Mt. Hagen", IsActive = true, IsDistrict = true, },
                new City { Id = 641, Description = "Popondetta", IsActive = true, IsDistrict = true, },
                new City { Id = 642, Description = "Rabaul", IsActive = true, IsDistrict = true, },
                new City { Id = 643, Description = "Vanimo", IsActive = true, IsDistrict = true, },
                new City { Id = 644, Description = "Wewak", IsActive = true, IsDistrict = true, },
                new City { Id = 645, Description = "Tabubil", IsActive = true, IsDistrict = true, },
                new City { Id = 646, Description = "Kieta", IsActive = true, IsDistrict = true, },
                new City { Id = 647, Description = "Laloata", IsActive = true, IsDistrict = true, },
                new City { Id = 648, Description = "Asuncion", IsActive = true, IsDistrict = true, },
                new City { Id = 649, Description = "Lima", IsActive = true, IsDistrict = true, },
                new City { Id = 650, Description = "Cuzco", IsActive = true, IsDistrict = true, },
                new City { Id = 651, Description = "Puno", IsActive = true, IsDistrict = true, },
                new City { Id = 652, Description = "Manila", IsActive = true, IsDistrict = true, },
                new City { Id = 653, Description = "Bacolod City", IsActive = true, IsDistrict = true, },
                new City { Id = 654, Description = "Cagayan De Oro", IsActive = true, IsDistrict = true, },
                new City { Id = 655, Description = "Calatagan", IsActive = true, IsDistrict = true, },
                new City { Id = 656, Description = "Cebu City", IsActive = true, IsDistrict = true, },
                new City { Id = 657, Description = "Dava City", IsActive = true, IsDistrict = true, },
                new City { Id = 658, Description = "Laoag", IsActive = true, IsDistrict = true, },
                new City { Id = 659, Description = "Olongapo City", IsActive = true, IsDistrict = true, },
                new City { Id = 660, Description = "Tagatay", IsActive = true, IsDistrict = true, },
                new City { Id = 661, Description = "Ternate", IsActive = true, IsDistrict = true, },
                new City { Id = 662, Description = "Taeloban", IsActive = true, IsDistrict = true, },
                new City { Id = 663, Description = "Banaue", IsActive = true, IsDistrict = true, },
                new City { Id = 664, Description = "Baguio City", IsActive = true, IsDistrict = true, },
                new City { Id = 665, Description = "Warsaw", IsActive = true, IsDistrict = true, },
                new City { Id = 666, Description = "Warsaw (Elsewhere)", IsActive = true, IsDistrict = true, },
                new City { Id = 667, Description = "London", IsActive = true, IsDistrict = true, }

                );
        }
    }
}
