using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SenateData.DataModels.Common;
namespace SenateData.Configurations
{
    public class CountrySeeder: IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.HasData(
                new Country { Id = 1, Description = "Afghanistan", IsActive = true, },
                new Country { Id = 2, Description = "Albania", IsActive = true, },
                new Country { Id = 3, Description = "Algeria ", IsActive = true, },
                new Country { Id = 4, Description = "Andorra", IsActive = true, },
                new Country { Id = 5, Description = "Angola", IsActive = true, },
                new Country { Id = 6, Description = "Antigua and Barbuda", IsActive = true, },
                new Country { Id = 7, Description = "Argentina ", IsActive = true, },
                new Country { Id = 8, Description = "Armenia", IsActive = true, },
                new Country { Id = 9, Description = "Australia", IsActive = true, },
                new Country { Id = 10, Description = "Austria", IsActive = true, },
                new Country { Id = 11, Description = "Azerbaijan ", IsActive = true, },
                new Country { Id = 12, Description = "Bahamas", IsActive = true, },
                new Country { Id = 13, Description = "Bahrain", IsActive = true, },
                new Country { Id = 14, Description = "Bangladesh", IsActive = true, },
                new Country { Id = 15, Description = "Barbados", IsActive = true, },
                new Country { Id = 16, Description = "Belarus", IsActive = true, },
                new Country { Id = 17, Description = "Belgium ", IsActive = true, },
                new Country { Id = 18, Description = "Belize", IsActive = true, },
                new Country { Id = 19, Description = "Benin", IsActive = true, },
                new Country { Id = 20, Description = "Bhutan", IsActive = true, },
                new Country { Id = 21, Description = "Bolivia", IsActive = true, },
                new Country { Id = 22, Description = "Bosnia and Herzegovina", IsActive = true, },
                new Country { Id = 23, Description = "Botswana ", IsActive = true, },
                new Country { Id = 24, Description = "Brazil", IsActive = true, },
                new Country { Id = 25, Description = "Brunei Darussalam", IsActive = true, },
                new Country { Id = 26, Description = "Burkina Faso", IsActive = true, },
                new Country { Id = 27, Description = "Burundi ", IsActive = true, },
                new Country { Id = 28, Description = "Cambodia", IsActive = true, },
                new Country { Id = 29, Description = "Cameroon", IsActive = true, },
                new Country { Id = 30, Description = "Canada", IsActive = true, },
                new Country { Id = 31, Description = "Cape Verde", IsActive = true, },
                new Country { Id = 32, Description = "Central African Republic", IsActive = true, },
                new Country { Id = 33, Description = "Chad", IsActive = true, },
                new Country { Id = 34, Description = "Chile", IsActive = true, },
                new Country { Id = 35, Description = "China", IsActive = true, },
                new Country { Id = 36, Description = "Colombia", IsActive = true, },
                new Country { Id = 37, Description = "Comoros", IsActive = true, },
                new Country { Id = 38, Description = "Congo", IsActive = true, },
                new Country { Id = 39, Description = "Congo, D R (Zaire)", IsActive = true, },
                new Country { Id = 40, Description = "Costa Rica", IsActive = true, },
                new Country { Id = 41, Description = "Cote d Ivoire", IsActive = true, },
                new Country { Id = 42, Description = "Croatia", IsActive = true, },
                new Country { Id = 43, Description = "Cuba", IsActive = true, },
                new Country { Id = 44, Description = "Cyprus", IsActive = true, },
                new Country { Id = 45, Description = "Czech Republic ", IsActive = true, },
                new Country { Id = 46, Description = "Denmark", IsActive = true, },
                new Country { Id = 47, Description = "Djibouti ", IsActive = true, },
                new Country { Id = 48, Description = "Dominica", IsActive = true, },
                new Country { Id = 49, Description = "Dominican Republic ", IsActive = true, },
                new Country { Id = 50, Description = "East Timor", IsActive = true, },
                new Country { Id = 51, Description = "Ecuador", IsActive = true, },
                new Country { Id = 52, Description = "Egypt", IsActive = true, },
                new Country { Id = 53, Description = "El Salvador", IsActive = true, },
                new Country { Id = 54, Description = "Equatorial Guinea", IsActive = true, },
                new Country { Id = 55, Description = "Eritrea", IsActive = true, },
                new Country { Id = 56, Description = "Estonia", IsActive = true, },
                new Country { Id = 57, Description = "Ethiopia ", IsActive = true, },
                new Country { Id = 58, Description = "Fiji", IsActive = true, },
                new Country { Id = 59, Description = "Finland", IsActive = true, },
                new Country { Id = 60, Description = "France", IsActive = true, },
                new Country { Id = 61, Description = "Gabon", IsActive = true, },
                new Country { Id = 62, Description = "Gambia", IsActive = true, },
                new Country { Id = 63, Description = "Georgia", IsActive = true, },
                new Country { Id = 64, Description = "Germany", IsActive = true, },
                new Country { Id = 65, Description = "Ghana", IsActive = true, },
                new Country { Id = 66, Description = "Greece", IsActive = true, },
                new Country { Id = 67, Description = "Grenada ", IsActive = true, },
                new Country { Id = 68, Description = "Guatemala", IsActive = true, },
                new Country { Id = 69, Description = "Guinea", IsActive = true, },
                new Country { Id = 70, Description = "Guinea-Bissau", IsActive = true, },
                new Country { Id = 71, Description = "Guyana", IsActive = true, },
                new Country { Id = 72, Description = "Haiti", IsActive = true, },
                new Country { Id = 73, Description = "Honduras", IsActive = true, },
                new Country { Id = 74, Description = "Hungary", IsActive = true, },
                new Country { Id = 75, Description = "Iceland", IsActive = true, },
                new Country { Id = 76, Description = "India ", IsActive = true, },
                new Country { Id = 77, Description = "Indonesia", IsActive = true, },
                new Country { Id = 78, Description = "Iran", IsActive = true, },
                new Country { Id = 79, Description = "Iraq ", IsActive = true, },
                new Country { Id = 80, Description = "Ireland", IsActive = true, },
                new Country { Id = 81, Description = "Israel", IsActive = true, },
                new Country { Id = 82, Description = "Italy ", IsActive = true, },
                new Country { Id = 83, Description = "Jamaica", IsActive = true, },
                new Country { Id = 84, Description = "Japan", IsActive = true, },
                new Country { Id = 85, Description = "Jordan", IsActive = true, },
                new Country { Id = 86, Description = "Kazakhstan", IsActive = true, },
                new Country { Id = 87, Description = "Kenya ", IsActive = true, },
                new Country { Id = 88, Description = "Kiribati", IsActive = true, },
                new Country { Id = 89, Description = "Korea, North", IsActive = true, },
                new Country { Id = 90, Description = "Korea, South ", IsActive = true, },
                new Country { Id = 91, Description = "Kuwait", IsActive = true, },
                new Country { Id = 92, Description = "Kyrgyzstan", IsActive = true, },
                new Country { Id = 93, Description = "Laos", IsActive = true, },
                new Country { Id = 94, Description = "Latvia", IsActive = true, },
                new Country { Id = 95, Description = "Lebanon ", IsActive = true, },
                new Country { Id = 96, Description = "Lesotho", IsActive = true, },
                new Country { Id = 97, Description = "Liberia", IsActive = true, },
                new Country { Id = 98, Description = "Libya ", IsActive = true, },
                new Country { Id = 99, Description = "Liechtenstein", IsActive = true, },
                new Country { Id = 100, Description = "Lithuania", IsActive = true, },
                new Country { Id = 101, Description = "Luxembourg", IsActive = true, },
                new Country { Id = 102, Description = "Macedonia", IsActive = true, },
                new Country { Id = 103, Description = "Madagascar", IsActive = true, },
                new Country { Id = 104, Description = "Malawi", IsActive = true, },
                new Country { Id = 105, Description = "Malaysia", IsActive = true, },
                new Country { Id = 106, Description = "Maldives", IsActive = true, },
                new Country { Id = 107, Description = "Mali ", IsActive = true, },
                new Country { Id = 108, Description = "Malta", IsActive = true, },
                new Country { Id = 109, Description = "Maritnique", IsActive = true, },
                new Country { Id = 110, Description = "Mauritania", IsActive = true, },
                new Country { Id = 111, Description = "Mauritius", IsActive = true, },
                new Country { Id = 112, Description = "Mexico", IsActive = true, },
                new Country { Id = 113, Description = "Micronesia ", IsActive = true, },
                new Country { Id = 114, Description = "Moldova", IsActive = true, },
                new Country { Id = 115, Description = "Monaco", IsActive = true, },
                new Country { Id = 116, Description = "Mongolia", IsActive = true, },
                new Country { Id = 117, Description = "Morocco", IsActive = true, },
                new Country { Id = 118, Description = "Mozambique", IsActive = true, },
                new Country { Id = 119, Description = "Myanmar", IsActive = true, },
                new Country { Id = 120, Description = "Namibia", IsActive = true, },
                new Country { Id = 121, Description = "Nauru", IsActive = true, },
                new Country { Id = 122, Description = "Nepal ", IsActive = true, },
                new Country { Id = 123, Description = "Netherlands", IsActive = true, },
                new Country { Id = 124, Description = "New Zealand", IsActive = true, },
                new Country { Id = 125, Description = "Nicaragua ", IsActive = true, },
                new Country { Id = 126, Description = "Niger", IsActive = true, },
                new Country { Id = 127, Description = "Nigeria", IsActive = true, },
                new Country { Id = 128, Description = "Northern Ireland (U.K.)", IsActive = true, },
                new Country { Id = 129, Description = "Norway ", IsActive = true, },
                new Country { Id = 130, Description = "Oman", IsActive = true, },
                new Country { Id = 131, Description = "Pakistan", IsActive = true, },
                new Country { Id = 132, Description = "Palau", IsActive = true, },
                new Country { Id = 133, Description = "Palestinian State ", IsActive = true, },
                new Country { Id = 134, Description = "Panama", IsActive = true, },
                new Country { Id = 135, Description = "Papua New Guinea", IsActive = true, },
                new Country { Id = 136, Description = "Paraguay", IsActive = true, },
                new Country { Id = 137, Description = "Peru ", IsActive = true, },
                new Country { Id = 138, Description = "The Philippines", IsActive = true, },
                new Country { Id = 139, Description = "Poland", IsActive = true, },
                new Country { Id = 140, Description = "Portugal ", IsActive = true, },
                new Country { Id = 141, Description = "Qatar", IsActive = true, },
                new Country { Id = 142, Description = "Romania", IsActive = true, },
                new Country { Id = 143, Description = "Russia", IsActive = true, },
                new Country { Id = 144, Description = "Rwanda", IsActive = true, },
                new Country { Id = 145, Description = "St. Kitts and Nevis", IsActive = true, },
                new Country { Id = 146, Description = "St. Lucia", IsActive = true, },
                new Country { Id = 147, Description = "St. Vincent and The Grenadines", IsActive = true, },
                new Country { Id = 148, Description = "Samoa", IsActive = true, },
                new Country { Id = 149, Description = "San Marino", IsActive = true, },
                new Country { Id = 150, Description = "Sao Tome and Principe", IsActive = true, },
                new Country { Id = 151, Description = "Saudi Arabia", IsActive = true, },
                new Country { Id = 152, Description = "Scotland (U.K.)", IsActive = true, },
                new Country { Id = 153, Description = "Senegal", IsActive = true, },
                new Country { Id = 154, Description = "Serbia and Montenegro", IsActive = true, },
                new Country { Id = 155, Description = "Seychelles", IsActive = true, },
                new Country { Id = 156, Description = "Sierra Leone", IsActive = true, },
                new Country { Id = 157, Description = "Singapore", IsActive = true, },
                new Country { Id = 158, Description = "Slovakia", IsActive = true, },
                new Country { Id = 159, Description = "Slovenia", IsActive = true, },
                new Country { Id = 160, Description = "Solomon Islands", IsActive = true, },
                new Country { Id = 161, Description = "Somalia", IsActive = true, },
                new Country { Id = 162, Description = "South Africa ", IsActive = true, },
                new Country { Id = 163, Description = "Spain", IsActive = true, },
                new Country { Id = 164, Description = "Sri Lanka", IsActive = true, },
                new Country { Id = 165, Description = "Sudan", IsActive = true, },
                new Country { Id = 166, Description = "Suriname", IsActive = true, },
                new Country { Id = 167, Description = "Swaziland", IsActive = true, },
                new Country { Id = 168, Description = "Sweden", IsActive = true, },
                new Country { Id = 169, Description = "Switzerland", IsActive = true, },
                new Country { Id = 170, Description = "Syria", IsActive = true, },
                new Country { Id = 171, Description = "Taiwan", IsActive = true, },
                new Country { Id = 172, Description = "Tajikistan", IsActive = true, },
                new Country { Id = 173, Description = "Tanzania ", IsActive = true, },
                new Country { Id = 174, Description = "Thailand", IsActive = true, },
                new Country { Id = 175, Description = "Togo", IsActive = true, },
                new Country { Id = 176, Description = "Tonga", IsActive = true, },
                new Country { Id = 177, Description = "Trinidad and Tobago ", IsActive = true, },
                new Country { Id = 178, Description = "Tunisia", IsActive = true, },
                new Country { Id = 179, Description = "Turkey", IsActive = true, },
                new Country { Id = 180, Description = "Turkmenistan", IsActive = true, },
                new Country { Id = 181, Description = "Tuvalu", IsActive = true, },
                new Country { Id = 182, Description = "Uganda", IsActive = true, },
                new Country { Id = 183, Description = "Ukraine ", IsActive = true, },
                new Country { Id = 184, Description = "United Arab Emirates", IsActive = true, },
                new Country { Id = 185, Description = "United Kingdom", IsActive = true, },
                new Country { Id = 186, Description = "United States ", IsActive = true, },
                new Country { Id = 187, Description = "Uruguay", IsActive = true, },
                new Country { Id = 188, Description = "Uzbekistan ", IsActive = true, },
                new Country { Id = 189, Description = "Vanuatu", IsActive = true, },
                new Country { Id = 190, Description = "Vatican City ", IsActive = true, },
                new Country { Id = 191, Description = "Venezuela", IsActive = true, },
                new Country { Id = 192, Description = "Vietnam", IsActive = true, },
                new Country { Id = 193, Description = "Wales (U.K.)", IsActive = true, },
                new Country { Id = 194, Description = "Western Sahara", IsActive = true, },
                new Country { Id = 195, Description = "Yemen ", IsActive = true, },
                new Country { Id = 196, Description = "Yugoslavia ", IsActive = true, },
                new Country { Id = 197, Description = "Zaire", IsActive = true, },
                new Country { Id = 198, Description = "Zambia ", IsActive = true, },
                new Country { Id = 199, Description = "Zimbabwe", IsActive = true, },
                new Country { Id = 200, Description = "Hong Kong", IsActive = true, },
                new Country { Id = 201, Description = "Phillipines", IsActive = true, },
                new Country { Id = 202, Description = "Anguilla", IsActive = true, },
                new Country { Id = 203, Description = "American Samoa", IsActive = true, },
                new Country { Id = 204, Description = "Belmopan", IsActive = true, },
                new Country { Id = 205, Description = "Bermuda", IsActive = true, },
                new Country { Id = 206, Description = "Birtish Virgin Islands", IsActive = true, },
                new Country { Id = 207, Description = "Bulgaria", IsActive = true, },
                new Country { Id = 208, Description = "Canary Islands", IsActive = true, },
                new Country { Id = 209, Description = "Cayman Islands", IsActive = true, },
                new Country { Id = 210, Description = "Cook Islands", IsActive = true, },
                new Country { Id = 211, Description = "French Guinea", IsActive = true, },
                new Country { Id = 212, Description = "Gibraltar", IsActive = true, },
                new Country { Id = 213, Description = "Greenland", IsActive = true, },
                new Country { Id = 214, Description = "Guadeloupe", IsActive = true, },
                new Country { Id = 215, Description = "Guam", IsActive = true, },
                new Country { Id = 216, Description = "Macro", IsActive = true, },
                new Country { Id = 217, Description = "Montserrat", IsActive = true, },
                new Country { Id = 218, Description = "Netherlands Antilles", IsActive = true, },
                new Country { Id = 219, Description = "New Calendonia", IsActive = true, },
                new Country { Id = 220, Description = "Niue", IsActive = true, }
                );
        }
    }
}
