using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SenateData.DataModels.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SenateData.Configurations
{
    public class PostSeeder
    {
        public void Configure(EntityTypeBuilder<Post> builder)
        {
            builder.HasData(
                    new Post { Id = 1, Description = "Secretary", IsActive = true, },
                    new Post { Id = 2, Description = "Additional Secretary", IsActive = true, },
                    new Post { Id = 3, Description = "Joint Secretary", IsActive = true, },
                    new Post { Id = 4, Description = "Deputy Secretary", IsActive = true, },
                    new Post { Id = 5, Description = "Assistant Secretary", IsActive = false, },
                    new Post { Id = 6, Description = "Section Officer", IsActive = true, },
                    new Post { Id = 7, Description = "Superintendent", IsActive = true, },
                    new Post { Id = 8, Description = "Assistant", IsActive = true, },
                    new Post { Id = 9, Description = "Upper Division Clerk", IsActive = true, },
                    new Post { Id = 10, Description = "Lower Division Clerk", IsActive = true, },
                    new Post { Id = 11, Description = "Stenographer", IsActive = true, },
                    new Post { Id = 12, Description = "Stenotypist (Eng.)", IsActive = true, },
                    new Post { Id = 13, Description = "Urdu Typist ", IsActive = true, },
                    new Post { Id = 14, Description = "Secretary To Chairman", IsActive = true, },
                    new Post { Id = 15, Description = "Director General (Computerization)", IsActive = false, },
                    new Post { Id = 16, Description = "Director General Research", IsActive = true, },
                    new Post { Id = 17, Description = "Director (Public Relations)", IsActive = true, },
                    new Post { Id = 18, Description = "Director (International Relations)", IsActive = false, },
                    new Post { Id = 19, Description = "Director (Inter-Parliamentary Affairs)", IsActive = false, },
                    new Post { Id = 20, Description = "Director Kashmir Committee (Coordination)", IsActive = false, },
                    new Post { Id = 21, Description = "Senior Reporter", IsActive = true, },
                    new Post { Id = 22, Description = "Chief Reporter", IsActive = true, },
                    new Post { Id = 23, Description = "Staff Officer", IsActive = true, },
                    new Post { Id = 24, Description = "P.S. To Deputy Chairman", IsActive = false, },
                    new Post { Id = 25, Description = "P.S. To Additional Secretary", IsActive = false, },
                    new Post { Id = 26, Description = "P.A. To Secretary", IsActive = false, },
                    new Post { Id = 27, Description = "Deputy Director (Media)", IsActive = true, },
                    new Post { Id = 28, Description = "Deputy Director (IT)", IsActive = true, },
                    new Post { Id = 29, Description = "Deputy Director (Lan/Programmer)", IsActive = true, },
                    new Post { Id = 30, Description = "Finance & Accounts Officer", IsActive = true, },
                    new Post { Id = 31, Description = "Officer On Special Duty (Pac)", IsActive = false, },
                    new Post { Id = 32, Description = "Lady Liaison Officer", IsActive = false, },
                    new Post { Id = 33, Description = "Sergeant-At-Arms", IsActive = true, },
                    new Post { Id = 34, Description = "Chief Editor Of Debates", IsActive = true, },
                    new Post { Id = 35, Description = "Director Translation", IsActive = true, },
                    new Post { Id = 36, Description = "Interpreter (National Languages)", IsActive = false, },
                    new Post { Id = 37, Description = "Interpreter", IsActive = true, },
                    new Post { Id = 38, Description = "Engineer Incharge (SIS)", IsActive = true, },
                    new Post { Id = 39, Description = "System Analyst", IsActive = true, },
                    new Post { Id = 40, Description = "Official Reporter (Urdu)", IsActive = true, },
                    new Post { Id = 41, Description = "Assistant Director Reporting", IsActive = true, },
                    new Post { Id = 42, Description = "Speech Writer (National Languages)", IsActive = true, },
                    new Post { Id = 43, Description = "Librarian", IsActive = true, },
                    new Post { Id = 44, Description = "Senior Research Officer", IsActive = true, },
                    new Post { Id = 45, Description = "Aps To Chairman", IsActive = true, },
                    new Post { Id = 46, Description = "P.S. To Chairman Kashmir Committee", IsActive = false, },
                    new Post { Id = 47, Description = "P.S. To Secretary", IsActive = false, },
                    new Post { Id = 48, Description = "P.S. To Additional Secretary", IsActive = false, },
                    new Post { Id = 49, Description = "Assistant Director (Pr)", IsActive = false, },
                    new Post { Id = 50, Description = "Assistant Director Protocol", IsActive = true, },
                    new Post { Id = 51, Description = "Assistant Director (Computer Publications)", IsActive = true, },
                    new Post { Id = 52, Description = "Deputy Sergeant-At-Arms", IsActive = true, },
                    new Post { Id = 53, Description = "Assistant Director Debates", IsActive = true, },
                    new Post { Id = 54, Description = "Official Reporter", IsActive = true, },
                    new Post { Id = 55, Description = "Assistant Reporter", IsActive = true, },
                    new Post { Id = 56, Description = "Translator (Selection Grade)", IsActive = true, },
                    new Post { Id = 57, Description = "Computer Programmer", IsActive = true, },
                    new Post { Id = 58, Description = "Deputy Librarian", IsActive = false, },
                    new Post { Id = 59, Description = "Assistant Director Research ", IsActive = false, },
                    new Post { Id = 60, Description = "Assistant Director Protocol ", IsActive = false, },
                    new Post { Id = 61, Description = "Interpreter-Cum Translator", IsActive = true, },
                    new Post { Id = 62, Description = "Assistant Director Translation", IsActive = true, },
                    new Post { Id = 63, Description = "Junior Engineer", IsActive = true, },
                    new Post { Id = 64, Description = "Sub-Engineer", IsActive = true, },
                    new Post { Id = 65, Description = "Assistant Librarian", IsActive = true, },
                    new Post { Id = 66, Description = "Word Processing/Operation Manager", IsActive = true, },
                    new Post { Id = 67, Description = "Caligraphist", IsActive = false, },
                    new Post { Id = 68, Description = "Cameraman", IsActive = true, },
                    new Post { Id = 69, Description = "Assistant Sergeant-At-Arms", IsActive = true, },
                    new Post { Id = 70, Description = "Transport Assistant", IsActive = true, },
                    new Post { Id = 71, Description = "Protocol Assistant", IsActive = true, },
                    new Post { Id = 72, Description = "Security Assistant", IsActive = true, },
                    new Post { Id = 73, Description = "Maintenance Supervisor", IsActive = false, },
                    new Post { Id = 74, Description = "Chief Proof Reader", IsActive = true, },
                    new Post { Id = 75, Description = "Microfilm Cameraman", IsActive = true, },
                    new Post { Id = 76, Description = "Micro Form Technician", IsActive = false, },
                    new Post { Id = 77, Description = "Data Entry Operator", IsActive = true, },
                    new Post { Id = 78, Description = "Lady Typist-Cum Receptionist", IsActive = false, },
                    new Post { Id = 79, Description = "Senior Proof Reader", IsActive = true, },
                    new Post { Id = 80, Description = "Junior Security Assistant", IsActive = true, },
                    new Post { Id = 81, Description = "Proof Reader", IsActive = true, },
                    new Post { Id = 82, Description = "Copy Holder", IsActive = true, },
                    new Post { Id = 83, Description = "Senior Comparer", IsActive = true, },
                    new Post { Id = 84, Description = "Telephone Attendant", IsActive = true, },
                    new Post { Id = 85, Description = "Oriental Section Clerk", IsActive = false, },
                    new Post { Id = 86, Description = "Book Binder", IsActive = true, },
                    new Post { Id = 87, Description = "Cutting & Binding Machine Operator", IsActive = false, },
                    new Post { Id = 88, Description = "Senior Off-Set Machine Operator", IsActive = true, },
                    new Post { Id = 89, Description = "Dispatch Rider", IsActive = true, },
                    new Post { Id = 90, Description = "Staff Car Driver", IsActive = true, },
                    new Post { Id = 91, Description = "Duplicating Machine Operator", IsActive = true, },
                    new Post { Id = 92, Description = "Chamber Attendant", IsActive = true, },
                    new Post { Id = 93, Description = "Record Sorter", IsActive = true, },
                    new Post { Id = 94, Description = "Library Attendant", IsActive = false, },
                    new Post { Id = 95, Description = "Daftry", IsActive = true, },
                    new Post { Id = 96, Description = "Qasid", IsActive = true, },
                    new Post { Id = 97, Description = "Naib Qasid", IsActive = true, },
                    new Post { Id = 99, Description = "Secretary, Mcc Cell Of Kashmir Committee", IsActive = true, },
                    new Post { Id = 100, Description = "Director, Kashmir Affairs, Mcc Cell Of Kashmir Committee", IsActive = false, },
                    new Post { Id = 101, Description = "Director, Media, Mcc Cell Of Kashmir Committee", IsActive = false, },
                    new Post { Id = 102, Description = "Director (Research & Publication), Mcc Cell Of Kashmir Committee", IsActive = false, },
                    new Post { Id = 103, Description = "Research Fellow, Mcc Cell Of Kashmir Committee", IsActive = true, },
                    new Post { Id = 104, Description = "Accounts Officer, Mcc Cell Of Kashmir Committee", IsActive = false, },
                    new Post { Id = 105, Description = "Public Relation Officer", IsActive = true, },
                    new Post { Id = 106, Description = "Director General Interpretation", IsActive = true, },
                    new Post { Id = 108, Description = "Director General Reporting", IsActive = true, },
                    new Post { Id = 109, Description = "Addl.C.P.R", IsActive = true, },
                    new Post { Id = 110, Description = "Director Reporting", IsActive = true, },
                    new Post { Id = 111, Description = "Engineer Incharge", IsActive = false, },
                    new Post { Id = 113, Description = "Electrician", IsActive = true, },
                    new Post { Id = 114, Description = "Electrical Supervisor", IsActive = true, },
                    new Post { Id = 115, Description = "Junior Assistant", IsActive = true, },
                    new Post { Id = 116, Description = "Junior Binder", IsActive = true, },
                    new Post { Id = 117, Description = "Assistant Caretaker", IsActive = true, },
                    new Post { Id = 118, Description = "Printing & Publication Officer", IsActive = true, },
                    new Post { Id = 119, Description = "Assistant Director Media", IsActive = true, },
                    new Post { Id = 120, Description = "Chief Comparer", IsActive = true, },
                    new Post { Id = 121, Description = "Senior Binder", IsActive = true, },
                    new Post { Id = 123, Description = "Stenotypist (Urdu)", IsActive = true, },
                    new Post { Id = 124, Description = "Deputy Director Debates", IsActive = true, },
                    new Post { Id = 125, Description = "TV Technician", IsActive = true, },
                    new Post { Id = 126, Description = "Deputy Director Media", IsActive = true, },
                    new Post { Id = 128, Description = "Supervisor Transport", IsActive = true, },
                    new Post { Id = 130, Description = "Advocate,Distt.", IsActive = false, },
                    new Post { Id = 131, Description = "Auditor", IsActive = false, },
                    new Post { Id = 132, Description = "D.S (Law)", IsActive = false, },
                    new Post { Id = 133, Description = "Guard", IsActive = false, },
                    new Post { Id = 134, Description = "J.M.C.", IsActive = false, },
                    new Post { Id = 135, Description = "J.S.A.", IsActive = false, },
                    new Post { Id = 137, Description = "Jr.Urdu Report", IsActive = false, },
                    new Post { Id = 138, Description = "L.D.C.", IsActive = false, },
                    new Post { Id = 139, Description = "Peon", IsActive = false, },
                    new Post { Id = 140, Description = "Postal Clerk", IsActive = false, },
                    new Post { Id = 141, Description = "Prot.Off/Supdt.", IsActive = false, },
                    new Post { Id = 142, Description = "Research Eco.", IsActive = false, },
                    new Post { Id = 143, Description = "Revisor", IsActive = false, },
                    new Post { Id = 144, Description = "Assistant Incharge", IsActive = true, },
                    new Post { Id = 145, Description = "PSO to Chairman", IsActive = true, },
                    new Post { Id = 146, Description = "Tech.Asstt.", IsActive = false, },
                    new Post { Id = 147, Description = "O.S.D.", IsActive = true, },
                    new Post { Id = 148, Description = "Visiting Reporter", IsActive = true, },
                    new Post { Id = 149, Description = "Driver", IsActive = true, },
                    new Post { Id = 152, Description = "Urdu Section Clerk", IsActive = true, },
                    new Post { Id = 153, Description = "Farrash Cum Chowkidar", IsActive = true, },
                    new Post { Id = 154, Description = "Chief Interpreter", IsActive = true, },
                    new Post { Id = 155, Description = "Deputy Dir. (Protocol)", IsActive = true, },
                    new Post { Id = 156, Description = "Asst. Protocol Officer", IsActive = false, },
                    new Post { Id = 157, Description = "Asst. P.R.O.", IsActive = false, },
                    new Post { Id = 158, Description = "P. A.", IsActive = true, },
                    new Post { Id = 159, Description = "Sr. Copy Holder", IsActive = true, },
                    new Post { Id = 160, Description = "Data Processing Asst.", IsActive = true, },
                    new Post { Id = 161, Description = "Security Guard", IsActive = true, },
                    new Post { Id = 162, Description = "Special Secretary", IsActive = true, },
                    new Post { Id = 165, Description = "Assistant Director (IT)", IsActive = true, },
                    new Post { Id = 167, Description = "Director Protocol", IsActive = true, },
                    new Post { Id = 169, Description = "Finance and Accounts Officer", IsActive = false, },
                    new Post { Id = 171, Description = "Director Computer", IsActive = true, },
                    new Post { Id = 172, Description = "Telephone Supervisor", IsActive = true, },
                    new Post { Id = 173, Description = "Addtl. Chief Copy Holder", IsActive = true, },
                    new Post { Id = 174, Description = "Waiter", IsActive = true, },
                    new Post { Id = 176, Description = "Assistant Cameraman", IsActive = true, },
                    new Post { Id = 178, Description = "Deputy Director Reporting", IsActive = true, },
                    new Post { Id = 179, Description = "Assistant Director (Reporting)", IsActive = false, },
                    new Post { Id = 182, Description = "Senior Librarian", IsActive = true, },
                    new Post { Id = 183, Description = "Assistant Director Interpretation", IsActive = true, },
                    new Post { Id = 184, Description = "Assistant Protocol Officer", IsActive = true, },
                    new Post { Id = 185, Description = "Deputy Director Protocol", IsActive = true, },
                    new Post { Id = 186, Description = "Director Interpretation", IsActive = true, },
                    new Post { Id = 187, Description = "Assistant Media Officer", IsActive = true, },
                    new Post { Id = 189, Description = "Director General Translation", IsActive = true, },
                    new Post { Id = 190, Description = "Deputy Director (Translation)", IsActive = true, },
                    new Post { Id = 191, Description = "Producer", IsActive = true, },
                    new Post { Id = 192, Description = "Data Control Administrator", IsActive = true, },
                    new Post { Id = 193, Description = "Director", IsActive = true, },
                    new Post { Id = 194, Description = "Director Debates", IsActive = true, },
                    new Post { Id = 195, Description = "Extra", IsActive = true, },
                    new Post { Id = 196, Description = "Director Research", IsActive = true, },
                    new Post { Id = 197, Description = "Cafeteria Manager", IsActive = true, },
                    new Post { Id = 198, Description = "Director Public Relations", IsActive = true, },
                    new Post { Id = 199, Description = "Director General Editing", IsActive = true, },
                    new Post { Id = 203, Description = "Stenographer", IsActive = false, },
                    new Post { Id = 204, Description = "Assistant Director Research", IsActive = true, },
                    new Post { Id = 206, Description = "Naib Qasid", IsActive = true, },
                    new Post { Id = 208, Description = "Deputy Director Research", IsActive = true, },
                    new Post { Id = 209, Description = "P.S. to Chief Whip", IsActive = false, },
                    new Post { Id = 210, Description = "Associate Engineer (CCTV)", IsActive = true, },
                    new Post { Id = 212, Description = "Sub Assistant", IsActive = true, },
                    new Post { Id = 213, Description = "Cleaner/Conductor/Naib Qasid", IsActive = true, },
                    new Post { Id = 214, Description = "Security Guard/NQ", IsActive = false, },
                    new Post { Id = 215, Description = "Sweeper", IsActive = true, },
                    new Post { Id = 216, Description = "Mali", IsActive = true, },
                    new Post { Id = 218, Description = "Advisor/Consultant (Law)", IsActive = false, },
                    new Post { Id = 219, Description = "Messenger Boy", IsActive = true, },
                    new Post { Id = 220, Description = "Gunman", IsActive = true, },
                    new Post { Id = 222, Description = "Head Waiter/Assistant", IsActive = true, },
                    new Post { Id = 224, Description = "Senior Private Secretary", IsActive = true, },
                    new Post { Id = 225, Description = "Kitchen Helper", IsActive = true, },
                    new Post { Id = 226, Description = "Private Secretary", IsActive = true, },
                    new Post { Id = 227, Description = "Cook", IsActive = true, },
                    new Post { Id = 228, Description = "Consultant", IsActive = true, },
                    new Post { Id = 229, Description = "Assistant Public Relation Officer", IsActive = true, },
                    new Post { Id = 230, Description = "Asstt. Media Officer", IsActive = true, },
                    new Post { Id = 231, Description = "Telephone Operator", IsActive = true, },
                    new Post { Id = 232, Description = "Director General Public Relations", IsActive = true, },
                    new Post { Id = 233, Description = "Research Officer", IsActive = true, },
                    new Post { Id = 234, Description = "Jamadar", IsActive = true, },
                    new Post { Id = 235, Description = "Asstt.Director Reporter", IsActive = true, },
                    new Post { Id = 236, Description = "Additional Chief Proof Reader", IsActive = true, },
                    new Post { Id = 237, Description = "Editor of Debates", IsActive = true, },
                    new Post { Id = 240, Description = "Condector", IsActive = true, },
                    new Post { Id = 242, Description = "Senior Binder", IsActive = false, },
                    new Post { Id = 243, Description = "Assistant Director Library", IsActive = true, },
                    new Post { Id = 244, Description = "Deputy Director Library", IsActive = true, },
                    new Post { Id = 245, Description = "Sr. Private Secretary", IsActive = false, },
                    new Post { Id = 246, Description = "Deputy Director Interpretation", IsActive = true, },
                    new Post { Id = 247, Description = "Sr.Copy Holder", IsActive = true, },
                    new Post { Id = 248, Description = "Aditional S.A.A", IsActive = true, },
                    new Post { Id = 249, Description = "Director(Media)", IsActive = true, },
                    new Post { Id = 250, Description = "Assistant Private Secretary", IsActive = true, },
                    new Post { Id = 253, Description = "Director (printing and publication)", IsActive = true, },
                    new Post { Id = 261, Description = "Supervisor HRM Database", IsActive = true, },
                    new Post { Id = 265, Description = "Deputy Director (P&P)", IsActive = true, },
                    new Post { Id = 266, Description = "Assistant Director (P&P)", IsActive = true, },
                    new Post { Id = 267, Description = "IT Assistant", IsActive = true, },
                    new Post { Id = 268, Description = "Director Staff", IsActive = true, },
                    new Post { Id = 269, Description = "Assistant IT Officer", IsActive = true, },
                    new Post { Id = 271, Description = "Policy Research Officer", IsActive = true, },
                    new Post { Id = 272, Description = "Director Coordination & Outreach", IsActive = true, },
                    new Post { Id = 273, Description = "AD Research-Cum-Speech Writer", IsActive = true, },
                    new Post { Id = 274, Description = "Director General Debate", IsActive = true, },
                    new Post { Id = 275, Description = "Offset Machine Operator", IsActive = true, },
                    new Post { Id = 276, Description = "Gift Packer", IsActive = true, },
                    new Post { Id = 277, Description = "DS (Acting Charge)", IsActive = true, },
                    new Post { Id = 278, Description = "Orderly", IsActive = true, },
                    new Post { Id = 279, Description = "Binding Incharge", IsActive = true, },
                    new Post { Id = 280, Description = "Cutting & Binding Machine Operator", IsActive = true, },
                    new Post { Id = 281, Description = "Electrical Supervisor", IsActive = false, },
                    new Post { Id = 282, Description = "Staff Assistant", IsActive = true, },
                    new Post { Id = 283, Description = "Security Officer to Chairman", IsActive = true, },
                    new Post { Id = 284, Description = "Assistant Incharge", IsActive = true, },
                    new Post { Id = 285, Description = "Assitant Incharge", IsActive = true, },
                    new Post { Id = 286, Description = "Assistant Incharge", IsActive = true, },
                    new Post { Id = 287, Description = "Assistant Incharge", IsActive = true, },
                    new Post { Id = 288, Description = "PSO to Chairman", IsActive = true, },
                    new Post { Id = 289, Description = "PSO to Chairman", IsActive = true, },
                    new Post { Id = 290, Description = "temppost", IsActive = true, },
                    new Post { Id = 291, Description = "Chief Editor", IsActive = true, },
                    new Post { Id = 292, Description = "Chief Editor", IsActive = true, },
                    new Post { Id = 293, Description = "Protocol Officer", IsActive = true, },
                    new Post { Id = 294, Description = "Director General Protocol/Media", IsActive = true, },
                    new Post { Id = 295, Description = "Lower Division Clerk", IsActive = true, },
                    new Post { Id = 296, Description = "Senior Interpreter", IsActive = true, },
                    new Post { Id = 297, Description = "Deputy Director Projects", IsActive = true, },
                    new Post { Id = 298, Description = "Assistant Director Library", IsActive = false, },
                    new Post { Id = 299, Description = "Assistant Draftsman", IsActive = true, },
                    new Post { Id = 300, Description = "Deputy Draftsman", IsActive = true, },
                    new Post { Id = 301, Description = "Senior Translator", IsActive = true, },
                    new Post { Id = 302, Description = "Jr. Messenger Clerk", IsActive = true, },
                    new Post { Id = 303, Description = "Additional Sergeant-at-Arms", IsActive = true, },
                    new Post { Id = 304, Description = "Senior Editor of Debates", IsActive = true, },
                    new Post { Id = 305, Description = "Director (IT)", IsActive = true, },
                    new Post { Id = 306, Description = "Data Processing /ICT Supervisor", IsActive = true, },
                    new Post { Id = 307, Description = "Deputy Director (LAN)", IsActive = true, },
                    new Post { Id = 308, Description = "Director General (IT)", IsActive = true, },
                    new Post { Id = 309, Description = "Director (LAN)", IsActive = true, },
                    new Post { Id = 310, Description = "Assistant Engineer", IsActive = true, },
                    new Post { Id = 311, Description = "Director Printing & Publication", IsActive = true, },
                    new Post { Id = 312, Description = "Protocol Attendant", IsActive = true, },
                    new Post { Id = 313, Description = "Assistant Secretary (Committees)", IsActive = true, },
                    new Post { Id = 314, Description = "Deputy Secretary (Committees)", IsActive = true, },
                    new Post { Id = 315, Description = "Supervisor Administration", IsActive = true, },
                    new Post { Id = 316, Description = "Senior Director General", IsActive = true, },
                    new Post { Id = 317, Description = "Senior Director Staff", IsActive = true, },
                    new Post { Id = 318, Description = "Assistant Director (Editing)", IsActive = true, },
                    new Post { Id = 319, Description = "Assistant Finance & Accounts Officer", IsActive = true, },
                    new Post { Id = 320, Description = "Instructor Drill & Security", IsActive = true, },
                    new Post { Id = 321, Description = "Accounts Officer", IsActive = true, },
                    new Post { Id = 322, Description = "Not Mentioned", IsActive = true, },
                    new Post { Id = 323, Description = "Associate Engineer (CCTV)", IsActive = true, },
                    new Post { Id = 324, Description = "D.D.O(Drawing & Disbursing Officer)", IsActive = true, },
                    new Post { Id = 325, Description = "Director Editing", IsActive = true, },
                    new Post { Id = 326, Description = "Deputy Director (Editing)", IsActive = true, },
                    new Post { Id = 327, Description = "Section Officer (Acting Charge)", IsActive = true, },
                    new Post { Id = 328, Description = "Assistant Director(Legislative Drafting)", IsActive = true, },
                    new Post { Id = 329, Description = "Senior Messenger Clerk", IsActive = true, },
                    new Post { Id = 330, Description = "Senior Finance And Accounts Officer", IsActive = true, },
                    new Post { Id = 331, Description = "Junior F&AO", IsActive = true, },
                    new Post { Id = 332, Description = "Assistant Director(Telecasting)", IsActive = true, },
                    new Post { Id = 333, Description = "House Attendance Officer", IsActive = true, },
                    new Post { Id = 334, Description = "Assistant Director Photography", IsActive = true, },
                    new Post { Id = 335, Description = "Lady Messenger Clerk ", IsActive = true, },
                    new Post { Id = 336, Description = "Lady Junior Security Assistant", IsActive = true, },
                    new Post { Id = 337, Description = "Lady Security Assistant ", IsActive = true, },
                    new Post { Id = 338, Description = "Senior Copy Holder", IsActive = true, },
                    new Post { Id = 339, Description = "Addl. Chief Copy Holder", IsActive = true, },
                    new Post { Id = 340, Description = "Chief Copy Holder", IsActive = true, },
                    new Post { Id = 341, Description = "Comparer", IsActive = true, },
                    new Post { Id = 342, Description = "Graphic Desinger", IsActive = true, },
                    new Post { Id = 343, Description = "Additional Comparer", IsActive = true, },
                    new Post { Id = 344, Description = "Assistant Director", IsActive = true, },
                    new Post { Id = 345, Description = "Translator", IsActive = true, },
                    new Post { Id = 346, Description = "Deputy Director (Legislative Drafting)", IsActive = true, },
                    new Post { Id = 347, Description = "Director General", IsActive = true, },
                    new Post { Id = 348, Description = "Head Chamber Attendant", IsActive = true, },
                    new Post { Id = 349, Description = "Addl. Chief Proof Reader", IsActive = true, },
                    new Post { Id = 350, Description = "Personal Attendant", IsActive = true, },
                    new Post { Id = 351, Description = "Dispatch Rider", IsActive = true, },
                    new Post { Id = 352, Description = "Assistant Director (Research Cum Speech Writer)", IsActive = true, },
                    new Post { Id = 353, Description = "Senior Waiter", IsActive = true, },
                    new Post { Id = 354, Description = "Additional Cheif Comparer", IsActive = true, },
                    new Post { Id = 355, Description = "Section Officer/DDO", IsActive = true, },
                    new Post { Id = 356, Description = "Extraa 2018", IsActive = false, },
                    new Post { Id = 357, Description = "Coordinator", IsActive = true, },
                    new Post { Id = 358, Description = "Personal Assistant", IsActive = true, },
                    new Post { Id = 359, Description = "Principal Secretary to Chairman", IsActive = true, },
                    new Post { Id = 360, Description = "Secretary General", IsActive = true, },
                    new Post { Id = 361, Description = "Acting Secretary", IsActive = true, },
                    new Post { Id = 362, Description = "Assistant House Attendant", IsActive = true, },
                    new Post { Id = 363, Description = "Assistant Engineer Civil", IsActive = true, },
                    new Post { Id = 364, Description = "Director General (Coordination)", IsActive = true, },
                    new Post { Id = 365, Description = "Assistant Research Officer", IsActive = true, },
                    new Post { Id = 366, Description = "Junior IT-Assistant", IsActive = true, },
                    new Post { Id = 367, Description = "Junior Protocol Assistant", IsActive = true, },
                    new Post { Id = 368, Description = "Receptonist", IsActive = true, },
                    new Post { Id = 369, Description = "Deputy Director (Litigation)", IsActive = true, },
                    new Post { Id = 370, Description = "Assistant Director (Litigation)", IsActive = true, },
                    new Post { Id = 371, Description = "Senior Protocol Attendant", IsActive = true, },
                    new Post { Id = 372, Description = "Junior Associate Engineer (CCTV)", IsActive = true, },
                    new Post { Id = 373, Description = "Special Security Official To Chairman", IsActive = true, },
                    new Post { Id = 374, Description = "Director General (Protocol", IsActive = true, }

                );
        }
    }
}
